/*
 * Project: dp-api-common
 * File:	DpQueryException.java
 * Package: com.ospreydcs.dp.api.query.model
 * Type: 	DpQueryException
 *
 * Copyright 2010-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * @author Christopher K. Allen
 * @org    OspreyDCS
 * @since Jan 10, 2024
 *
 * TODO:
 * - None
 */
package com.ospreydcs.dp.api.query.model;

/**
 *
 * <p>
 * General exception generated by Data Platform Query Service operations. 
 * </p>
 * 
 * @author Christopher K. Allen
 * @since Jan 10, 2024
 *
 */
public class DpQueryException extends Exception {

    private static final long serialVersionUID = 1L;

    /**
     * <p>
     * Constructs a new instance of <code>DpQueryException</code>.
     * </p>
     *
     */
    public DpQueryException() {
    }

    /**
     * <p>
     * Constructs a new instance of <code>DpQueryException</code>.
     * </p>
     *
     * @param message           exception message
     */
    public DpQueryException(String message) {
        super(message);
    }

    /**
     * <p>
     * Constructs a new instance of <code>DpQueryException</code>.
     * </p>
     *
     * @param cause             source of the general exception
     */
    public DpQueryException(Throwable cause) {
        super(cause);
    }

    /**
     * <p>
     * Constructs a new instance of <code>DpQueryException</code>.
     * </p>
     *
     * @param message           exception message
     * @param cause             source of the general exception
     */
    public DpQueryException(String message, Throwable cause) {
        super(message, cause);
    }

    /**
     * <p>
     * Constructs a new instance of <code>DpQueryException</code>.
     * </p>
     *
     * @param message           exception message
     * @param cause             source of the general exception
     * @param enableSuppression whether or not exception suppression should be enabled
     * @param writableStackTrace whether or not stack trace operation should be enabled
     */
    public DpQueryException(String message, Throwable cause, boolean enableSuppression, boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }

}
