/*
 * Project: dp-jal
 * File:	IDatumFactory.java
 * Package: com.ospreydcs.dp.jal.tools.common.datagen
 * Type: 	IDatumFactory
 *
 * Copyright 2010-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * @author Christopher K. Allen
 * @org    OspreyDCS
 * @since Dec 3, 2025
 *
 */
package com.ospreydcs.dp.jal.tools.common.datagen;

import com.ospreydcs.dp.jal.common.DpSupportedType;

/**
 * <p>
 * Required operations for all generators of simulated, heterogeneous data.
 * </p>
 * <p>
 * Implementations are assumed to create a sequence of artificial data where the type and values within
 * the sequence are determined by the implementation and its configuration.
 * Data are created one value at a time, (i.e., a "datum") with the <code>{@link #nextDatum()}</code>
 * operation. 
 * </p>
 *
 *
 * @author Christopher K. Allen
 * @since Dec 3, 2025
 *
 */
public interface IDatumFactory {

    
    //
    // Configuration
    //
    
    /**
     * <p>
     * Returns the Data Platform supported type of the simulated data returned by <code>{@link #nextDatum()}</code>.
     * </p>
     * <p>
     * Returns the type constant in enumeration <code>{@link DpSupportedType}</code> of the value
     * generated by this data value factory.  Note that constants within <code>{@link DpSupportedTYpe}</code>
     * can represent both scalar and complex data types.
     * </p> 
     * 
     * @return  the enumeration constant representing the value types returned by <code>{@link #nextDatum()}</code>
     */
    public DpSupportedType  getDatumType();
    
    
    /**
     * <p>
     * Returns the scalar-value type of composite simulated data produced by this factory.
     * </p>
     * <p>
     * Note that complex data types are built from scalar-value data.  Thus, if this factory produces complex data types, 
     * the underlying data values within the complex data structures are eventually scalar.  This method returns 
     * the data type of these scalar values.
     * </p>
     * <p>
     * If the complex type has no underlying composite scalar type the value <code>{@link JalScalarType#UNSUPPORTED}</code>
     * is returned.
     * </p>
     *  
     * @return  the scalar type of the composite data within complex data structures produced by this factory
     */
    public JalScalarType    getScalarType();
    
    /**
     * <p>
     * Returns the complex data type of the simulated data values created by this factory.
     * </p>
     * <p>
     * If this factory instance produces scalar values than the constant <code>{@link JalComplexType#SCALAR}</code>
     * is returned.
     * </p>
     * 
     * @return  the enumeration constant representing the complex type of simulated data produced by this factory
     */
    public JalComplexType    getComplexType();

    
    //
    // Operations
    //
    
    /**
     * <p>
     * Returns the next simulated data value in the value sequence.
     * </p>
     * 
     * @return  next value in generated sequence as a Java <code>Object</code>
     */
    public Object nextDatum();
    
}
