/*
 * Project: dp-jal
 * File:	IDataColumnFactory.java
 * Package: com.ospreydcs.dp.jal.tools.common.datagen
 * Type: 	IDataColumnFactory
 *
 * Copyright 2010-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * @author Christopher K. Allen
 * @org    OspreyDCS
 * @since Dec 1, 2025
 *
 */
package com.ospreydcs.dp.jal.tools.common.datagen;

import com.ospreydcs.dp.jal.common.DpSupportedType;
import com.ospreydcs.dp.jal.common.IDataColumn;

/**
 * <p>
 * Required operations for implementations creating data columns of simulated, heterogeneous data.
 * </p>
 *
 * @author Christopher K. Allen
 * @since Dec 1, 2025
 *
 */
public interface IDataColumnFactory<T extends Object> {

    
    //
    // Configuration
    //
    
    /**
     * <p>
     * Returns the column name for all factory generated columns.
     * </p>
     * <p>
     * All data columns generated by <code>{@link #nextColumnn()}</code> will have a name given
     * by the returned value.
     * </p>
     * 
     * @return  column name for factory generated columns
     */
    public String           getColumnName();
    
    /**
     * <p>
     * Returns the size of each column generated, that is, the number of values in the column.
     * </p>
     * <p>
     * The returned value is also interpreted as the number of column rows.  This context is particular
     * to ingestion frames having multiple columns of with the same number of rows.  Thus, all
     * data columns generated by <code>{@link #nextColumnn()}</code> should contain the returned number
     * of values. 
     * </p>
     * 
     * @return  number column values (or "rows")
     */
    public int              getColumnSize();
    
    /**
     * <p>
     * The Data Platform type enumeration for the column values.
     * </p>
     * <p>
     * All simulated data values within data columns generated by <code>{@link #nextColumnn()}</code>
     * should the data type identified by the returned enumeration constant.
     * </p>
     *   
     * @return  the <code>DpSupported</code> type enumeration for column data values
     */
    public DpSupportedType  getColumnType();
    
    
    // 
    // Operations
    //
    
    /**
     * <p>
     * Creates a new data columns according to the configuration of this <code>IDataColumnFactory</code> instance.
     * </p>
     * <p>
     * Simulated data values for the data column are generally created by an <code>{@link IDatumFactory}</code>
     * provided to the <code>IDataColumnFactory</code> implementation at construction.
     * The type parameter for the new column is given by <code>{@link #getColumnType()}</code>
     * and the size of the column (i.e., number of rows) is given by <code>{@link #getColumnSize()}</code>.
     * </p>
     * 
     * @return  new implementation of the <code>IDataColumn</code> interface populated with simulated data
     */
    public IDataColumn<T>   nextColumn();
    
}
