/*
 * Project: dp-api-common
 * File:	DpDataset.java
 * Package: com.ospreydcs.dp.api.common
 * Type: 	DpDataset
 *
 * Copyright 2010-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * @author Christopher K. Allen
 * @org    OspreyDCS
 * @since Feb 28, 2025
 *
 */
package com.ospreydcs.dp.api.common;

import java.util.List;

import com.ospreydcs.dp.api.annotate.model.DpDataBlock;
import com.ospreydcs.dp.api.grpc.util.ProtoMsg;
import com.ospreydcs.dp.grpc.v1.annotation.DataBlock;
import com.ospreydcs.dp.grpc.v1.annotation.DataSet;

/**
 * <p>
 * Record defining the properties and attributes of an Annotation Service "Data Set."
 * </p>
 * <p>
 * <h2>Data Sets</h2>
 * This record describes all the properties of a data set within the Data Platform time-series
 * data archive.  Data sets are collections of "data blocks" within the archive, the full collection
 * of data blocks forming a basis set for the time-series data archive query domain.  Data sets have
 * other defining attributes associated with the Data Platform, such an UID, an owner, a name, and an 
 * optional description string.
 * </p>
 * <p>
 * <h2>Data Sets Query</h2>
 * This record is intended as the result of a data sets query request.  Such requests are initiated with
 * a <code>DpDatasetsRequest</code> instance offered to the Annotation Service API 
 * <code>IAnnotationService</code>.  Data sets requests are used to identify and recover data sets 
 * previously created by Data Platform clients.  Once the results are obtained they can be used to
 * recover annotations with the Data Platform archive, or create new annotations for the data set(s).
 * for more information on data sets query see the class documentation for 
 * <code>{@link DpDatasetsRequest}</code>.
 * </p>
 * <p>
 * <h2>Archive Annotations</h2>
 * To create an archive annotation the collection of time-series data being annotation must first be
 * identified, this is done using data sets.  Specifically, the archive region is defined by creating
 * the data set covering that region.  Once this data set is created, the region can be annotated.
 * Both data set creation and archive annotation are accomplished through the Annotation Service API
 * <code>IAnnotationService</code>.  For more information on data set creation see the class documentation
 * for <code>{@link DpCreateDatasetRequest}</code>. 
 * </p>  
 * <p>
 * <h2>Data Blocks</h2>
 * Recall that data sets are composed of collections of data blocks, which are fundamental basis
 * sets for the Data Platform time-series archive.
 * Data blocks are simply collections of data source names (i.e., Process Variable names), and a 
 * finite time range duration.  For more information on data blocks see the class documentation
 * for <code>{@link DpDataBlock}</code>.
 * </p>  
 * 
 * @param   datasetUid      unique identifier for the data set (generated by the Data Platform)
 * @param   ownerUid        unique identifier of the data set owner (e.g., creator)
 * @param   name            name of the data set (not necessarily unique)
 * @param   descr           string description of the data set (or <code>null</code> if not supplied)
 * @param   blocks          collection of data blocks forming the data set (should be immutable)
 *
 * @author Christopher K. Allen
 * @since Feb 28, 2025
 *
 */
public record DpDataset(DatasetUID datasetUid, 
                        OwnerUID ownerUid, 
                        String name, 
                        String descr, 
                        List<DpDataBlock> blocks) 
{
    
    //
    // Creators
    //
    
    /**
     * <p>
     * Creates a new <code>DpDataset</code> record populated with the data in the given Protocol Buffers message.
     * </p>
     * <p>
     * This operation is essentially a direct conversion from the Protocol Buffers message argument to a
     * Java record representing the contents of the message.  
     * </p>
     * <h2>NOTES:</h2>
     * The <code>DpDataset</code> record has the list field <code>blocks</code>.  In the returned instance this
     * field is immutable; any attempt to modify the list will throw an exception.
     * </p>
     * 
     * @param msgDataSet    Protocol Buffers data set message
     * 
     * @return  equivalent Java API Library data set record
     */
    public static DpDataset from(DataSet msgDataSet) {
        
        // Extract the message data
        DatasetUID      recDatasetUid = DatasetUID.from(msgDataSet.getId());
        OwnerUID        recOwnerUid = OwnerUID.from(msgDataSet.getOwnerId());
        String          strName = msgDataSet.getName();
        String          strDescr = msgDataSet.getDescription();
        List<DataBlock> lstMsgBlks = msgDataSet.getDataBlocksList();
        
        // Convert data blocks - This operation creates an immutable list of DpDataBlocks
        List<DpDataBlock> lstBlks = lstMsgBlks.stream().<DpDataBlock>map(ProtoMsg::toDataBlock).toList();
        
        // Create the record and return it
        DpDataset   dataset = new DpDataset(recDatasetUid, recOwnerUid, strName, strDescr, lstBlks);
        
        return dataset;
    }

    
    //
    // Constructors
    //
    
}
