#
# Project: dp-api-common
# File:    dp-api-config.yml
# Type:    YAML
#
# Author: Christopher K. Allen
# Since: December 21, 2023
#
# Default configuration parameters for the Data Platform API library common resources.
#
# This parameter set should be modified according to the Data Platform site installation
# and the platform where the API libraies are installed.
#
#
# GENERAL NOTES:
#
# - Most parameters can be left to their default values which are optimal for most platforms
#   and installation.
#
# - The 'connections:' section for all supported services WILL require modification for site 
#   installation.
#   Specifically, the 'channel: host:' parameters for each supported service connection must be
#   directed to the service address (URL) and port number of the server.
#        channel:
#           host:
#             url: Enter URL of the server provided desired service (e.g., Query, Ingestion, etc.)
#             port: Enter port number of server where service is located
#
# - Some API components have explicit event logging available.  
#      - Event logging can be activated by setting the 'active:' property to "true".
#
#      - Event logging configuration is specified in the companion resource file 'log4j2.xml'
#        and follows the Apache Log4J format for XML.
#        (see https://logging.apache.org/log4j/2.x/manual/configuration.html)
#
#      - Note that event logging can create a performance overhead and, thus, should typically
#        only be used for diagnostics.
#
# - All configuration parameters can be overridden using system variables.  
#   See the adjacent parameter comments for system variable names.
#
#    - In the current DP API configuration mechanism, overrides by system variables are as follows:
#      1. System environment variables overrides the configuration first.
#      2. System properties variables then overrides the configuration parameters.
#
#    - System environment variables are set using  standard commands of the host platform.
#      For examle, the 'export VARIABLE_NAME=value' command for Unix, or using the 'export'
#      command within the '.zprofile' file when using the Z shell.
#
#    - System property variables are taken from the 'java' command-line arguments line using
#      the '-D[VARIABLE_NAME]' option where VARIABLE_NAME is the system variable name.
#        java -jar -D[VARIABLE] DP-SERVICE_NAME_JAR
#
#
# gRPC NOTES:
#
# - Use of gRPC data compression typically slows overall transission significantly
#
# - gRPC maximum message size must be power of 2
#    2^26 = 67,108,864
#    2^25 = 33,554,432
#    2^24 = 16,777,216
#    2^23 =  8,388,608
#    2^22 =  4,194,304
#    2^21 =  2,097,152
#    2^20 =  1,048,576
#    2^19 =    524,288
#
# - Default gRPC maximum message size is 2^22 = 4194304
#
# - Looks like we want to keep gRPC maximum message size <= 2^24 = 16,777,216
#
#

archive:    # Data Platform data archive properties
   inception: 2023-09-01T00:00:00.0Z # ealiest archive timestamp      : DP_API_ARCHIVE_INCEPTION
   
query:      # Data Platform Query Service operations
   pageSize: 100      # UNUSED       # default bucket count per page  : DP_API_QUERY_PAGE_SIZE
   
   data:         # Parameters for time-series data queries
      request:        # Default parameters used in data requests
         composite:        # data request query decomposition (for multi-threading)
            active: true                # use query decomposition  : DP_API_QUERY_DATA_REQUEST_COMPOSITE_ACTIVE
            maxSources: 1000            # max data source count    : DP_API_QUERY_DATA_REQUEST_COMPOSITE_MAX_SOURCES
            maxDuration: 1000           # max time range duration  : DP_API_QUERY_DATA_REQUEST_COMPOSITE_MAX_DURATION
            unitDuration: MILLISECONDS  # java.concurrent.TimeUnit : DP_API_QUERY_DATA_REQUEST_COMPOSITE_UNIT_DURATION
      response:       # Default parameters used for data responses 
         multistream:      # Multiple gRPC data stream parameters
            active: true             # use multistreamed responses : DP_API_QUERY_DATA_RESPONSE_MULTISTREAM_ACTIVE
            pivotSize: 4000          # query domain size (srcs-time): DP_API_QUERY_DATA_RESPONSE_MULTISTREAM_PIVOT_SIZE
            pivotUnits: SECONDS      # java.concurrent.TimeUnit    : DP_API_QUERY_DATA_RESPONSE_MULTISTREAM_PIVOT_UNITS 
            maxStreams: 8            # maximum stream count        : DP_API_QUERY_DATA_RESPONSE_MULTISTREAM_MAX_STREAMS
            preference: UNIDIRECTIONAL  # {UNIDIRECTIONAL, BIDRECTIONAL} : DP_API_QUERY_DATA_RESPONSE_MULTISTREAM_PREFERENCE
   concurrency:  # General concurrency (multi-threading) properties
      active: true                   # use concurrency           : DP_API_QUERY_CONCURRENCY_ACTIVE
      pivotSize: 10                  # size inducing concurrency : DP_API_QUERY_CONCURRENCY_PIVOT_SIZE
      threadCount: 5                 # worker thread count       : DP_API_QUERY_CONCURRENCY_THREAD_COUNT
   timeout:      # General connection timeout properties (e.g., used in API interface shutdown)
      active: true                   # apply timeout condition   : DP_API_QUERY_TIMEOUT_ACTIVE
      limit: 30                      # timeout limit             : DP_API_QUERY_TIMEOUT_LIMIT
      unit: SECONDS                  # java.concurrent.TimeUnit  : DP_API_QUERY_TIMEOUT_UNIT
   logging:      # General Query Service logging services
      active: true                   # is logging active              : DP_API_QUERY_LOGGING_ACTIVE
      level: DEBUG                   # logger output level if active  : DP_API_QUERY_LOGGING_LEVEL
 
connections:   # All available Data Platform service connections
   ingestion:
      name: DP Ingestion Service     # (opt) name of connection  : DP_API_CONNECTION_INGESTION_NAME
      version: 1.0.0                 # (opt) parameters version  : DP_API_CONNECTION_INGESTION_VERSION
      description: Data Platform Ingestion Service default connection parameters # : DP_API_CONNECTION_INGESTION_DESCRIPTION 
      supplement: None               # (opt) anonymous parameter: DP_API_CONNECTION_INGESTION_SUPPLEMENT
      timeout:      # General connection timeout properties (e.g., used in service shutdown)
         active: true                # apply timeout condition   : DP_API_CONNECTION_INGESTION_TIMEOUT_ACTIVE
         limit: 30                   # timeout limit             : DP_API_CONNECTION_INGESTION_TIMEOUT_LIMIT
         unit: SECONDS               # java.concurrent.TimeUnit  : DP_API_CONNECTION_INGESTION_TIMEOUT_UNIT
      channel:      # gRPC Channel configuration         
         host:             # host server location 
            url: localhost              # host server URL           : DP_API_CONNECTION_INGESTION_CHANNEL_HOST_URL
            port: 50051                 # server port address       : DP_API_CONNECTION_INGESTION_CHANNEL_HOST_PORT
         tls:              # HTTP2 Transport Layer Security parameters
            active: false               # use TLS security          : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_ACTIVE
            defaultTls: true            # use default TLS operation : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_DEFAULT
            filepaths:     # file path locations for TLS certificates and keys (only if defaultTls == false)
               trustedCerts:            # trusted certs collection  : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_FILE_TRUSTED_CERTS
               clientCerts:             # client certificates chain : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_FILE_CLIENT_CERTS
               clientKey:               # client private key        : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_FILE_CLIENT_KEY
         grpc:             # gRPC transport parameters
            timeoutLimit: 20            # channel operation timeout : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_TIMEOUT_LIMIT
            timeoutUnit: SECONDS        # timeout units             : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_TIMEOUT_UNIT
            messageSizeMax: 4194304     # (bytes) max message size  : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_MESSAGE_SIZE_MAX
            usePlainText: false         # plain text transmission   : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_XMIT_PLAIN_TEXT   
            keepAliveWithoutCalls: false # channel never idle       : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_KEEP_ALIVE
            gzip: false                 # use gzip compression      : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_COMPRESS_GZIP
    
   query:
      name: DP Query Service         # (opt) name of connection  : DP_API_CONNECTION_QUERY_NAME
      version: 1.0.0                 # (opt) parameters version  : DP_API_CONNECTION_QUERY_VERSION
      description: Data Platform Query Service default connection parameters # : DP_API_CONNECTION_QUERY_DESCRIPTION
      supplement: None               # (opt) anonymous parameter : DP_API_CONNECTION_QUERY_SUPPLEMENT
      timeout:      # General connection timeout properties (e.g., used in service shutdown)
         active: true                # apply timeout condition   : DP_API_CONNECTION_QUERY_TIMEOUT_ACTIVE
         limit: 30                   # timeout limit             : DP_API_CONNECTION_QUERY_TIMEOUT_LIMIT
         unit: SECONDS               # java.concurrent.TimeUnit  : DP_API_CONNECTION_QUERY_TIMEOUT_UNIT
      channel:      # gRPC Channel configuration         
         host:             # host server location 
            url: localhost              # host server URL           : DP_API_CONNECTION_QUERY_CHANNEL_HOST_URL
            port: 50052                 # server port address       : DP_API_CONNECTION_QUERY_CHANNEL_HOST_PORT
         tls:              # HTTP2 Transport Layer Security parameters
            active: false               # use TLS security          : DP_API_CONNECTION_QUERY_CHANNEL_TLS_ACTIVE
            defaultTls: true            # use default TLS operation : DP_API_CONNECTION_QUERY_CHANNEL_TLS_DEFAULT
            filepaths:     # file path locations for TLS certificates and keys (only if defaultTls == false)
               trustedCerts:            # trusted certs collection  : DP_API_CONNECTION_QUERY_CHANNEL_TLS_FILE_TRUSTED_CERTS
               clientCerts:             # client certificates chain : DP_API_CONNECTION_QUERY_CHANNEL_TLS_FILE_CLIENT_CERTS
               clientKey:               # client private key        : DP_API_CONNECTION_QUERY_CHANNEL_TLS_FILE_CLIENT_KEY
         grpc:             # gRPC parameters
            timeoutLimit: 20            # channel operation timeout : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_TIMEOUT_LIMIT
            timeoutUnit: SECONDS        # timeout units             : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_TIMEOUT_UNIT
            messageSizeMax: 4194304     # (bytes) max message size  : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_MESSAGE_SIZE_MAX
            usePlainText: false         # plain text transmission   : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_XMIT_PLAIN_TEXT   
            keepAliveWithoutCalls: false # channel never idle       : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_KEEP_ALIVE
            gzip: false                 # use gzip compression      : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_COMPRESS_GZIP
    
   
