#
# Project: dp-api-common
# File:    dp-api-config.yml
# Type:    YAML
#
# Default configuration parameters for the Data Platform API library common resources.
#
# This parameter set should be modified according to the Data Platform site installation
# and the platform where the API libraies are installed.
#
# Author: Christopher K. Allen
# Since: December 21, 2023
#
#
# NOTES:
#
# - All configuration parameters can be overridden using system variables.  
#   See the adjacent parameter comments for system variable names.
#
# - System property variables are taken from the 'java' command-line arguments line using
#   the '-D[VARIABLE_NAME]' option where VARIABLE_NAME is the system variable name.
#     java -jar -D[VARIABLE] DP-SERVICE_NAME_JAR
#
# - In the current DP API configuration mechanism overrides by system variables are as follows:
#   1. System environment variables override this configuration first.
#   2. System properties variables then override.
#
# - In the current implementation service override environment variables affect ALL SERVICES.
#
# - Use of compression slows overall transission significantly
#
# - gRPC maximum message size must be power of 2
#    2^26 = 67,108,864
#    2^25 = 33,554,432
#    2^24 = 16,777,216
#    2^23 =  8,388,608
#    2^22 =  4,194,304
#    2^21 =  2,097,152
#    2^20 =  1,048,576
#    2^19 =    524,288
#
# - Default gRPC maximum message size is 2^22 = 4194304
#
# - Looks like we want to keep gRPC maximum message size <= 2^24 = 16,777,216
#

archive:
   inception: 2023-09-01T00:00:00.0Z # ealiest archive timestamp      : DP_API_ARCHIVE_INCEPTION
   
query:
   pageSize: 100                     # default bucket count per page  : DP_API_QUERY_PAGE_SIZE 
 
connections:   # All available Data Platform service connections
   ingestion:
      name: DP Ingestion Service     # (opt) name of connection  : DP_API_CONNECTION_INGESTION_NAME
      version: 1.0.0                 # (opt) parameters version  : DP_API_CONNECTION_INGESTION_VERSION
      description: Data Platform Ingestion Service default connection parameters # : DP_API_CONNECTION_INGESTION_DESCRIPTION 
      supplement: None               # (opt) anonymous parameter: DP_API_CONNECTION_INGESTION_SUPPLEMENT
      timeout:      # General connection timeout properties (e.g., used in service shutdown)
         active: true                # apply timeout condition   : DP_API_CONNECTION_INGESTION_TIMEOUT_ACTIVE
         limit: 30                   # timeout limit             : DP_API_CONNECTION_INGESTION_TIMEOUT_LIMIT
         unit: SECONDS               # java.concurrent.TimeUnit  : DP_API_CONNECTION_INGESTION_TIMEOUT_UNIT
      channel:      # gRPC Channel configuration         
         host:             # host server location 
            url: localhost              # host server URL           : DP_API_CONNECTION_INGESTION_CHANNEL_HOST_URL
            port: 50051                 # server port address       : DP_API_CONNECTION_INGESTION_CHANNEL_HOST_PORT
         tls:              # HTTP2 Transport Layer Security parameters
            active: true                # use TLS security          : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_ACTIVE
            defaultTls: true            # use default TLS operation : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_DEFAULT
            filepaths:     # file path locations for TLS certificates and keys (only if defaultTls == false)
               trustedCerts:            # trusted certs collection  : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_FILE_TRUSTED_CERTS
               clientCerts:             # client certificates chain : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_FILE_CLIENT_CERTS
               clientKey:               # client private key        : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_FILE_CLIENT_KEY
         grpc:             # gRPC transport parameters
            timeoutLimit: 20            # channel operation timeout : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_TIMEOUT_LIMIT
            timeoutUnit: SECONDS        # timeout units             : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_TIMEOUT_UNIT
            messageSizeMax: 4194304     # (bytes) max message size  : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_MESSAGE_SIZE_MAX
            usePlainText: false         # plain text transmission   : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_XMIT_PLAIN_TEXT   
            keepAliveWithoutCalls: false # channel never idle       : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_KEEP_ALIVE
            gzip: false                 # use gzip compression      : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_COMPRESS_GZIP
    
   query:
      name: DP Query Service         # (opt) name of connection  : DP_API_CONNECTION_QUERY_NAME
      version: 1.0.0                 # (opt) parameters version  : DP_API_CONNECTION_QUERY_VERSION
      description: Data Platform Query Service default connection parameters # : DP_API_CONNECTION_QUERY_DESCRIPTION
      supplement: None               # (opt) anonymous parameter : DP_API_CONNECTION_QUERY_SUPPLEMENT
      timeout:      # General connection timeout properties (e.g., used in service shutdown)
         active: true                # apply timeout condition   : DP_API_CONNECTION_QUERY_TIMEOUT_ACTIVE
         limit: 30                   # timeout limit             : DP_API_CONNECTION_QUERY_TIMEOUT_LIMIT
         unit: SECONDS               # java.concurrent.TimeUnit  : DP_API_CONNECTION_QUERY_TIMEOUT_UNIT
      channel:      # gRPC Channel configuration         
         host:             # host server location 
            url: localhost              # host server URL           : DP_API_CONNECTION_QUERY_CHANNEL_HOST_URL
            port: 50052                 # server port address       : DP_API_CONNECTION_QUERY_CHANNEL_HOST_PORT
         tls:              # HTTP2 Transport Layer Security parameters
            active: true                # use TLS security          : DP_API_CONNECTION_QUERY_CHANNEL_TLS_ACTIVE
            defaultTls: true            # use default TLS operation : DP_API_CONNECTION_QUERY_CHANNEL_TLS_DEFAULT
            filepaths:     # file path locations for TLS certificates and keys (only if defaultTls == false)
               trustedCerts:            # trusted certs collection  : DP_API_CONNECTION_QUERY_CHANNEL_TLS_FILE_TRUSTED_CERTS
               clientCerts:             # client certificates chain : DP_API_CONNECTION_QUERY_CHANNEL_TLS_FILE_CLIENT_CERTS
               clientKey:               # client private key        : DP_API_CONNECTION_QUERY_CHANNEL_TLS_FILE_CLIENT_KEY
         grpc:             # gRPC parameters
            timeoutLimit: 20            # channel operation timeout : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_TIMEOUT_LIMIT
            timeoutUnit: SECONDS        # timeout units             : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_TIMEOUT_UNIT
            messageSizeMax: 4194304     # (bytes) max message size  : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_MESSAGE_SIZE_MAX
            usePlainText: false         # plain text transmission   : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_XMIT_PLAIN_TEXT   
            keepAliveWithoutCalls: false # channel never idle       : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_KEEP_ALIVE
            gzip: false                 # use gzip compression      : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_COMPRESS_GZIP
    
   
