#
# Project: dp-api-common
# File:    dp-api-config.yml
# Type:    YAML
#
# Author: Christopher K. Allen
# Since: December 21, 2023
#
# Default configuration parameters for the Data Platform API library common resources.
#
# This parameter set should be modified according to the Data Platform site installation
# and the platform where the API libraies are installed.
#
#
# GENERAL NOTES:
#
# - Most parameters can be left to their default values which are optimal for most platforms
#   and installation.
#
# - Concurrency parameters should be tuned for the host platform.  General rule of thumb is to use thread
#   counts which are multiples of the number of CPU cores.  A safe choice for the thread count is the
#   number of CPU cores - 1 (providing 1 core for main thread).
#
# - The 'connections:' section for all supported services WILL require modification for site 
#   installation.
#   Specifically, the 'channel: host:' parameters for each supported service connection must be
#   directed to the service address (URL) and port number of the server.
#        channel:
#           host:
#             url: Enter URL of the server provided desired service (e.g., Query, Ingestion, etc.)
#             port: Enter port number of server where service is located
#
# - Some API components have explicit event logging available.  
#      - Event logging can be activated by setting the 'active:' property to "true".
#
#      - Event logging configuration is specified in the companion resource file 'log4j2.xml'
#        and follows the Apache Log4J format for XML.
#        (see https://logging.apache.org/log4j/2.x/manual/configuration.html)
#
#      - Note that event logging can create a performance overhead and, thus, should typically
#        only be used for diagnostics.
#
# - All configuration parameters can be overridden using system variables.  
#   See the adjacent parameter comments for system variable names.
#
#    - In the current DP API configuration mechanism, overrides by system variables are as follows:
#      1. System environment variables overrides the configuration first.
#      2. System properties variables then overrides the configuration parameters.
#
#    - System environment variables are set using  standard commands of the host platform.
#      For examle, the 'export VARIABLE_NAME=value' command for Unix, or using the 'export'
#      command within the '.zprofile' file when using the Z shell.
#
#    - System property variables are taken from the 'java' command-line arguments line using
#      the '-D[VARIABLE_NAME]' option where VARIABLE_NAME is the system variable name.
#        java -jar -D[VARIABLE] DP-SERVICE_NAME_JAR
#
#
# gRPC NOTES:
#
# - Use of gRPC data compression typically slows overall transission significantly
#
# - gRPC maximum message size must be power of 2
#    2^26 = 67,108,864
#    2^25 = 33,554,432
#    2^24 = 16,777,216
#    2^23 =  8,388,608
#    2^22 =  4,194,304
#    2^21 =  2,097,152
#    2^20 =  1,048,576
#    2^19 =    524,288
#
# - Default gRPC maximum message size is 2^22 = 4194304
#
# - Looks like we want to keep gRPC maximum message size <= 2^24 = 16,777,216
#
#

archive:    # Data Platform data archive properties
   inception: 2023-09-01T00:00:00.0Z # ealiest archive timestamp      : DP_API_ARCHIVE_INCEPTION
   
ingest: # Data Platform Ingestion Service client API default configuration parameters
   decompose:    # IngestionFrame decomposition parameters
      enabled: true               # use data binning            : DP_API_INGEST_DECOMPOSE_ACTIVE
      maxSize: 4000000            # max bin size (bytes)        : DP_API_INGEST_DECOMPOSE_MAX_SIZE
   stream:       # General gRPC streaming parameter for Ingestion Service operations
      enabled: true                 # use streaming parameters    : DP_API_INGEST_STREAM_ENABLED
      type: BIDIRECTIONAL           # preferred- {FORWARD, BIDIRECTIONAL} : DP_API_INGEST_STREAM_TYPE
      buffer:              # data buffering and queueing parameters (transmission staging)
         enabled: true               # enable data buffering/queue : DP_API_INGEST_STREAM_BUFFER_ENABLED
         size: 100                   # buffer/queue size (messages): DP_API_INGEST_STREAM_BUFFER_SIZE
         allocation: 400000000       # max buffer allocation (bytes): DP_API_INGEST_STREAM_BUFFER_ALLOCATION   
         backPressure : true         # enable ingestion throttling : DP_API_INGEST_STREAM_BUFFER_BACKPRESSURE
      concurrency:         # multiple,concurrent gRPC stream parameters
         enabled: true               # use multiple streams when possible : DP_API_INGEST_STREAM_CONCURRENCY_ENABLED
         pivotSize: 10               # currency activation size (frames)  : DP_API_INGEST_STREAM_CONCURRENCY_PIVOT_SIZE
         maxStreams: 3               # maximum number of streams to use   : DP_API_INGEST_STREAM_CONCURRENT_MAX_STREAMS
   concurrency:  # General concurrency (multi-threading) properties
      enabled: true                  # use concurrency            : DP_API_INGEST_CONCURRENCY_ENABLED
      pivotSize: 10                  # size inducing concurrency  : DP_API_INGEST_CONCURRENCY_PIVOT_SIZE
      maxThreads: 3                  # max worker thread count    : DP_API_INGEST_CONCURRENCY_MAX_THREADS
   timeout:      # General ingestion timeout properties (e.g., used for ingestion response wait timeout)
      enabled: true                   # apply timeout condition    : DP_API_INGEST_TIMEOUT_ENABLED
      limit: 10                      # request timeout limit      : DP_API_INGEST_TIMEOUT_LIMIT
      unit: SECONDS                  # java.concurrent.TimeUnit   : DP_API_INGEST_TIMEOUT_UNIT
   logging:      # General Ingestion Service logging services
      enabled: true                  # is logging active              : DP_API_INGEST_LOGGING_ACTIVE
      level: DEBUG                   # logger output level if active  : DP_API_INGEST_LOGGING_LEVEL

query:      # Data Platform Query Service client API default configuration parameters
   pageSize: 100      # UNUSED       # default bucket count per page  : DP_API_QUERY_PAGE_SIZE
   
   data:         # Configuration parameters for time-series data requests and recoveries
      request:        # Default parameters used in data requests
         stream:           # gRPC streaming default parameters
            preference: BACKWARD        # {BACKWARD, BIDRECTIONAL} : DP_API_QUERY_DATA_REQUEST_STREAM_PREFERENCE
         decompose:        # data request query decomposition default parameters (for multi-streaming)
            enabled: true           # use query decomposition  : DP_API_QUERY_DATA_REQUEST_COMPOSITE_ENABLED
            maxSources: 1000        # max data source count    : DP_API_QUERY_DATA_REQUEST_COMPOSITE_MAX_SOURCES
            maxDuration: 1          # max time duration (unit)  : DP_API_QUERY_DATA_REQUEST_COMPOSITE_MAX_DURATION
            durationUnit: SECONDS   # java.concurrent.TimeUnit : DP_API_QUERY_DATA_REQUEST_COMPOSITE_DURATION_UNIT
      response:       # Default parameters used for data responses
         correlate:        # Query data correlation parameters
            useConcurrency: true    # use mult-thread correlation : DP_API_QUERY_DATA_RESPONSE_CORRELATE_USE_CONCURRENCY
            whileStreaming: true    # correlate during gRPC stream: DP_API_QUERY_DATA_RESPONSE_CORRELATE_WHILE_STREAMING
         multistream:      # Multiple gRPC data stream parameters
            enabled: true            # use multistreamed responses : DP_API_QUERY_DATA_RESPONSE_MULTISTREAM_ENABLED
            maxStreams: 3            # maximum stream count        : DP_API_QUERY_DATA_RESPONSE_MULTISTREAM_MAX_STREAMS
            sizeDomain: 2000         # rqst domain size (samples-time) triggering ms : DP_API_QUERY_DATA_RESPONSE_MULTISTREAM_PIVOT_SIZE
      table:         # Default parameters used for time-series data table construction
         construction:      # General data table reconstruction parameters
            errorChecking: true      # use advanced error checking : DP_API_QUERY_DATA_TABLE_CONSTRUCTION_ERROR_CHECKING
            domainCollision: true    # allow/disallow time domain collision : DP_API_QUERY_DATA_TABLE_CONSTRUCTION_DOMAIN_COLLISION 
         sstatic:           # static data table properties 
            isDefault: true          # use static table as default  : DP_API_QUERY_DATA_TABLE_STATIC_DEFAULT
            hasMaxSize: true         # enforce maximum table size   : DP_API_QUERY_DATA_TABLE_STATIC_HAS_MAX_SIZE
            maxSize: 4000000         # maximum size (bytes) allowed : DP_API_QUERY_DATA_TABLE_STATIC_MAX_SIZE
         dynamic:           # dynamic data table properties
            enable: true             # enable dynamic data tables   : DP_API_QUERY_DATA_TABLE_DYNAMIC_ENABLE
   concurrency:  # General concurrency (multi-threading) properties
      enabled: true                  # use concurrency            : DP_API_QUERY_CONCURRENCY_ENABLED
      pivotSize: 10                  # size inducing concurrency  : DP_API_QUERY_CONCURRENCY_PIVOT_SIZE
      maxThreads: 20                 # max worker thread count    : DP_API_QUERY_CONCURRENCY_MAX_THREADS
   timeout:      # General query timeout properties (e.g., used for query response wait timeout)
      enabled: true                  # apply timeout condition    : DP_API_QUERY_TIMEOUT_ENABLED
      limit: 30                      # request timeout limit      : DP_API_QUERY_TIMEOUT_LIMIT
      unit: SECONDS                  # java.concurrent.TimeUnit   : DP_API_QUERY_TIMEOUT_UNIT
   logging:      # General Query Service API logging services
      enabled: true                  # is logging active              : DP_API_QUERY_LOGGING_ENABLED
      level: DEBUG                   # logger output level if active  : DP_API_QUERY_LOGGING_LEVEL
      
annotation:
   timeout:      # General query timeout properties (e.g., used for query response wait timeout)
      enabled: true                  # apply timeout condition    : DP_API_ANNOTATION_TIMEOUT_ENABLED
      limit: 30                      # request timeout limit      : DP_API_ANNOTATION_TIMEOUT_LIMIT
      unit: SECONDS                  # java.concurrent.TimeUnit   : DP_API_ANNOTATION_TIMEOUT_UNIT
   logging:      # General Annotation Service API logging services
      enabled: true                  # is logging active              : DP_API_ANNOTATION_LOGGING_ENABLED
      level: DEBUG                   # logger output level if active  : DP_API_ANNOTATION_LOGGING_LEVEL
 
connections:   # All available Data Platform service connections   
   logging:     # General event logging for all connection operations 
      enabled: true                  # is logging active              : DP_API_CONNECTION_LOGGING_ENABLED
      level: INFO                    # logger output level if active  : DP_API_CONNECTION_LOGGING_LEVEL
      
   ingestion:   # Ingestion Service connection
      name: DP Ingestion Service     # (opt) name of connection  : DP_API_CONNECTION_INGESTION_NAME
      version: 1.7.0                 # (opt) parameters version  : DP_API_CONNECTION_INGESTION_VERSION
      description: Data Platform Ingestion Service default connection parameters # : DP_API_CONNECTION_INGESTION_DESCRIPTION 
      supplement: None               # (opt) anonymous parameter: DP_API_CONNECTION_INGESTION_SUPPLEMENT
      timeout:      # General connection timeout properties (e.g., used in service shutdown)
         enabled: true               # timeout condition enabled : DP_API_CONNECTION_INGESTION_TIMEOUT_ENABLED
         limit: 30                   # timeout limit             : DP_API_CONNECTION_INGESTION_TIMEOUT_LIMIT
         unit: SECONDS               # java.concurrent.TimeUnit  : DP_API_CONNECTION_INGESTION_TIMEOUT_UNIT
      channel:      # gRPC Channel configuration         
         host:             # host server location 
            url: localhost              # host server URL           : DP_API_CONNECTION_INGESTION_CHANNEL_HOST_URL
            port: 50051                 # server port address       : DP_API_CONNECTION_INGESTION_CHANNEL_HOST_PORT
         tls:              # HTTP2 Transport Layer Security parameters
            enabled: false              # use TLS security          : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_ENABLED
            defaultTls: true            # use default TLS operation : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_DEFAULT
            filepaths:     # file path locations for TLS certificates and keys (only if defaultTls == false)
               trustedCerts:            # trusted certs collection  : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_FILE_TRUSTED_CERTS
               clientCerts:             # client certificates chain : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_FILE_CLIENT_CERTS
               clientKey:               # client private key        : DP_API_CONNECTION_INGESTION_CHANNEL_TLS_FILE_CLIENT_KEY
         grpc:             # gRPC transport parameters
            timeoutLimit: 20            # channel operation timeout : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_TIMEOUT_LIMIT
            timeoutUnit: SECONDS        # timeout units             : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_TIMEOUT_UNIT
            messageSizeMax: 4194304     # (bytes) max message size  : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_MESSAGE_SIZE_MAX
            usePlainText: false         # plain text transmission   : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_XMIT_PLAIN_TEXT   
            keepAliveWithoutCalls: false # channel never idle       : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_KEEP_ALIVE
            gzip: false                 # use gzip compression      : DP_API_CONNECTION_INGESTION_CHANNEL_GRPC_COMPRESS_GZIP
    
   query:   # Query Service connection
      name: DP Query Service         # (opt) name of connection  : DP_API_CONNECTION_QUERY_NAME
      version: 1.7.0                 # (opt) parameters version  : DP_API_CONNECTION_QUERY_VERSION
      description: Data Platform Query Service default connection parameters # : DP_API_CONNECTION_QUERY_DESCRIPTION
      supplement: None               # (opt) anonymous parameter : DP_API_CONNECTION_QUERY_SUPPLEMENT
      timeout:      # General connection timeout properties (e.g., used in service shutdown)
         enabled: true               # apply timeout condition   : DP_API_CONNECTION_QUERY_TIMEOUT_ENABLED
         limit: 30                   # timeout limit             : DP_API_CONNECTION_QUERY_TIMEOUT_LIMIT
         unit: SECONDS               # java.concurrent.TimeUnit  : DP_API_CONNECTION_QUERY_TIMEOUT_UNIT
      channel:      # gRPC Channel configuration         
         host:             # host server location 
            url: localhost              # host server URL           : DP_API_CONNECTION_QUERY_CHANNEL_HOST_URL
            port: 50052                 # server port address       : DP_API_CONNECTION_QUERY_CHANNEL_HOST_PORT
         tls:              # HTTP2 Transport Layer Security parameters
            enabled: false              # use TLS security          : DP_API_CONNECTION_QUERY_CHANNEL_TLS_ENABLED
            defaultTls: true            # use default TLS operation : DP_API_CONNECTION_QUERY_CHANNEL_TLS_DEFAULT
            filepaths:     # file path locations for TLS certificates and keys (only if defaultTls == false)
               trustedCerts:            # trusted certs collection  : DP_API_CONNECTION_QUERY_CHANNEL_TLS_FILE_TRUSTED_CERTS
               clientCerts:             # client certificates chain : DP_API_CONNECTION_QUERY_CHANNEL_TLS_FILE_CLIENT_CERTS
               clientKey:               # client private key        : DP_API_CONNECTION_QUERY_CHANNEL_TLS_FILE_CLIENT_KEY
         grpc:             # gRPC parameters
            timeoutLimit: 20            # channel operation timeout : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_TIMEOUT_LIMIT
            timeoutUnit: SECONDS        # timeout units             : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_TIMEOUT_UNIT
            messageSizeMax: 4194304     # (bytes) max message size  : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_MESSAGE_SIZE_MAX
            usePlainText: false         # plain text transmission   : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_XMIT_PLAIN_TEXT   
            keepAliveWithoutCalls: false # channel never idle       : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_KEEP_ALIVE
            gzip: false                 # use gzip compression      : DP_API_CONNECTION_QUERY_CHANNEL_GRPC_COMPRESS_GZIP
    
   annotation: # Annotation Service connection
      name: DP Annotation Service         # (opt) name of connection  : DP_API_CONNECTION_ANNOTATION_NAME
      version: 1.7.0                 # (opt) parameters version  : DP_API_CONNECTION_ANNOTATION_VERSION
      description: Data Platform Annotation Service default connection parameters # : DP_API_CONNECTION_ANNOTATION_DESCRIPTION
      supplement: None               # (opt) anonymous parameter : DP_API_CONNECTION_ANNOTATION_SUPPLEMENT
      timeout:      # General connection timeout properties (e.g., used in service shutdown)
         enabled: true               # apply timeout condition   : DP_API_CONNECTION_ANNOTATION_TIMEOUT_ENABLED
         limit: 30                   # timeout limit             : DP_API_CONNECTION_ANNOTATION_TIMEOUT_LIMIT
         unit: SECONDS               # java.concurrent.TimeUnit  : DP_API_CONNECTION_ANNOTATION_TIMEOUT_UNIT
      channel:      # gRPC Channel configuration         
         host:             # host server location 
            url: localhost              # host server URL           : DP_API_CONNECTION_ANNOTATION_CHANNEL_HOST_URL
            port: 50053                 # server port address       : DP_API_CONNECTION_ANNOTATION_CHANNEL_HOST_PORT
         tls:              # HTTP2 Transport Layer Security parameters
            enabled: false              # use TLS security          : DP_API_CONNECTION_ANNOTATION_CHANNEL_TLS_ENABLED
            defaultTls: true            # use default TLS operation : DP_API_CONNECTION_ANNOTATION_CHANNEL_TLS_DEFAULT
            filepaths:     # file path locations for TLS certificates and keys (only if defaultTls == false)
               trustedCerts:            # trusted certs collection  : DP_API_CONNECTION_ANNOTATION_CHANNEL_TLS_FILE_TRUSTED_CERTS
               clientCerts:             # client certificates chain : DP_API_CONNECTION_ANNOTATION_CHANNEL_TLS_FILE_CLIENT_CERTS
               clientKey:               # client private key        : DP_API_CONNECTION_ANNOTATION_CHANNEL_TLS_FILE_CLIENT_KEY
         grpc:             # gRPC parameters
            timeoutLimit: 20            # channel operation timeout : DP_API_CONNECTION_ANNOTATION_CHANNEL_GRPC_TIMEOUT_LIMIT
            timeoutUnit: SECONDS        # timeout units             : DP_API_CONNECTION_ANNOTATION_CHANNEL_GRPC_TIMEOUT_UNIT
            messageSizeMax: 4194304     # (bytes) max message size  : DP_API_CONNECTION_ANNOTATION_CHANNEL_GRPC_MESSAGE_SIZE_MAX
            usePlainText: false         # plain text transmission   : DP_API_CONNECTION_ANNOTATION_CHANNEL_GRPC_XMIT_PLAIN_TEXT   
            keepAliveWithoutCalls: false # channel never idle       : DP_API_CONNECTION_ANNOTATION_CHANNEL_GRPC_KEEP_ALIVE
            gzip: false                 # use gzip compression      : DP_API_CONNECTION_ANNOTATION_CHANNEL_GRPC_COMPRESS_GZIP
    
   
