/*
 * Project: dp-api-common
 * File:	JalIngestionException.java
 * Package: com.ospreydcs.dp.api.ingest.model
 * Type: 	JalIngestionException
 *
 * Copyright 2010-2023 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * @author Christopher K. Allen
 * @org    OspreyDCS
 * @since Mar 28, 2024
 *
 * TODO:
 * - None
 */
package com.ospreydcs.dp.api.ingest;

/**
 * <p>
 * General exception generated by Java client library Ingestion Service interface operations. 
 * </p>
 *
 * @author Christopher K. Allen
 * @since Mar 28, 2024
 *
 */
public class JalIngestionException extends Exception {


    /** Serialization identifier required by Serializable interface */
    private static final long serialVersionUID = 7792016301423454334L;

    
    //
    // Constructors
    //
    
    /**
     * <p>
     * Constructs a new instance of <code>JalIngestionException</code>.
     * </p>
     *
     */
    public JalIngestionException() {
    }

    /**
     * <p>
     * Constructs a new instance of <code>JalIngestionException</code> with detail message.
     * </p>
     *
     * @param message   string detail message describing exception
     */
    public JalIngestionException(String message) {
        super(message);
    }

    /**
     * <p>
     * Constructs a new instance of <code>JalIngestionException</code> caused by external exception.
     * </p>
     *
     * @param cause     root-cause exception (i.e., origin of current exception)
     */
    public JalIngestionException(Throwable cause) {
        super(cause);
    }

    /**
     * <p>
     * Constructs a new instance of <code>JalIngestionException</code> with detail message and root cause.
     * </p>
     *
     * @param message   string detail message describing exception (in addition to cause)
     * @param cause     root-cause exception (i.e., origin of current exception)
     */
    public JalIngestionException(String message, Throwable cause) {
        super(message, cause);
    }

    /**
     * <p>
     * Constructs a new instance of <code>JalIngestionException</code>.
     * </p>
     *
     * @param message               string detail message describing exception (in addition to cause)
     * @param cause                 root-cause exception (i.e., origin of current exception)
     * @param enableSuppression     suppression enabled switch
     * @param writableStackTrace    writable stack trace enable switch
     */
    public JalIngestionException(String message, 
            Throwable cause, 
            boolean enableSuppression,
            boolean writableStackTrace) 
    {
        super(message, cause, enableSuppression, writableStackTrace);
    }

}
