/*
 * Project: dp-jal
 * File:	DataColumnsFactory.java
 * Package: com.ospreydcs.dp.jal.tools.common.datagen.factories.frames
 * Type: 	DataColumnsFactory
 *
 * Copyright 2010-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * @author Christopher K. Allen
 * @org    OspreyDCS
 * @since Nov 18, 2025
 *
 */
package com.ospreydcs.dp.jal.tools.common.datagen.factories.frames;

import java.util.ArrayList;
import java.util.Set;

import com.ospreydcs.dp.jal.common.DpSupportedType;
import com.ospreydcs.dp.jal.common.IDataColumn;
import com.ospreydcs.dp.jal.model.table.StaticDataColumn;
import com.ospreydcs.dp.jal.tools.common.datagen.IDataColumnsFactory;
import com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory;
import com.ospreydcs.dp.jal.util.JavaRuntime;

/**
 * <p>
 * Factory class for simultaneous generation of multiple columns of simulated data.
 * </p>
 * <p>
 * This class is provided in addition to class <code>DataColumnFactory</code>, which creates single columns
 * at a time.  This class is capable of simultaneously generating multiple columns of <code>IDataColumn</code>
 * instances per <code>{@link #build()}</code> invocation.
 * </p>
 * <p>
 * Instances of this class are used primarily for column generation within ingestion frame factory class
 * instances.  This column factory creates multiple columns upon invocation of the <code>{@link #build()}</code>
 * method.  All data columns contain simulated data of the same data type, specifically, the data type
 * generated by the <code>{@link IDatumFactory}</code> instance provided at creation/construction. 
 * </p>
 * <p>
 * <h2>Column Generation</h2>
 * The <code>{@link #build()}</code> method is used to create vectors (i.e., <code>{@link ArrayList}</code>) of
 * <code>IDataColumn</code> objects according to the <code>DataColumnsFactory</code> configuration determined
 * at creation/construction.  The number of columns returned in the vector is given by the size of the
 * <code>{@link Set}</code> argument containing column names, while the type of each column data value is
 * given by <code>{@link IDatumFactory#getDatumType()}</code> of the data factory provided at creation/construction.  
 * Column values are generated using the <code>{@link IDatumFactory}</code> by sequential invocation of
 * <code>{@link IDatumFactory#nextDatum()}</code>.
 * </p>
 * <h2>Column Types</h2>
 * The data columns returned by the <code>{@link #build()}</code> method are implementations of the interface
 * <code>{@link IDataColumn}</code>.  Currently, the underlying implementation is of type
 * <code>{@link StaticDataColumn}</code>.
 * </p>
 * <p>
 * <h2>Column Count</h2>
 * The number of columns created in each invocation to <code>{@link #build()}</code> is the size of the set
 * of column names provided at creation/construction.
 * </p>
 * 
 *
 * @author Christopher K. Allen
 * @since Nov 18, 2025
 *
 */
public class DataColumnsFactory implements IDataColumnsFactory<Object> {

    
    //
    // Creators
    //
    
    /**
     * <p>
     * Creates and returns a new <code>DataColumnsFactory</code> instance configured according to the given arguments.
     * </p>
     * <p>
     * The <code>{@link #build()}</code> method is available for data column creation.  It returns a vector
     * (i.e., <code>{@link ArrayList}</code> of data columns, one for each column name given, containing simulated
     * data produced by the given data value factory.  The size of each column (i.e., the number of rows) is given 
     * by the size argument.
     * See the class documentation on <code>{@link DataColumnsFactory}</code> for more information.
     * </p>
     * 
     * @param setColNms set of unique column names
     * @param szCols    the size of each data column (i.e., number of rows)
     * @param facValues the data value factory producing simulated column values
     * 
     * @return  a new <code>DataColumnsFactory</code> instance ready for data column generation
     * 
     * @throws IllegalArgumentException either empty name collection, column size < 1, or value factory is <code>null</code>
     * 
     * @see DataColumnsFactory
     */
    public static final DataColumnsFactory from(Set<String> setColNms, IDatumFactory facValues) throws IllegalArgumentException {
        return new DataColumnsFactory(setColNms, facValues);
    }

    
    //
    // Defining Attributes - Configuration
    //
    
    /** The names of each column */
    private final Set<String>           setColNms; 
    
//    /** The size of each column - number of data values */
//    private final int                   szCols;
    
    /** The value factory for generating column values */
    private final IDatumFactory     facValues;
    
    
    //
    // Consistent Attributes
    //
    
    /** The number of columns to generate */
    private final int                   cntCols;
    
    /** The Data Platform supported data type of the data column */
    private final DpSupportedType       enmColType;
    
    
    //
    // Constructors
    //
    
    /**
     * <p>
     * Constructs a new <code>DataColumnsFactory</code> instance.
     * </p>
     *
     * @param setColNms set of unique column names
     * @param szCols    the size of each data column (i.e., number of rows)
     * @param facValues the data value factory producing simulated column values
     * 
     * @throws IllegalArgumentException either empty name collection, column size < 1, or value factory is <code>null</code>
     */
    public DataColumnsFactory(Set<String> setColNms, IDatumFactory facValues) throws IllegalArgumentException {
        
        // Check arguments
        if (setColNms.size() < 1)
            throw new IllegalArgumentException(JavaRuntime.getQualifiedMethodNameSimple() + " - Empty column name set.");
//        if (szCols < 1) 
//            throw new IllegalArgumentException(JavaRuntime.getQualifiedMethodNameSimple() + " - Column size must be > 0.");
        if (facValues == null)
            throw new IllegalArgumentException(JavaRuntime.getQualifiedMethodNameSimple() + " - Must provide a non-null value factory.");
        
        this.setColNms = setColNms;
//        this.szCols = szCols;
        this.facValues = facValues;
        
        this.cntCols = this.setColNms.size();
        this.enmColType = this.facValues.getDatumType();
    }

    
    //
    // IDataColumnsFactory Interface
    //
    
    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDataColumnsFactory#getColumnCount()
     */
    @Override
    public final int getColumnCount() {
        return this.cntCols;
    }
    
    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDataColumnsFactory#getColumnNames()
     */
    @Override
    public final Set<String> getColumnNames() {
        return this.setColNms;
    }
    
//    /**
//     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDataColumnsFactory#getColumnSize()
//     */
//    @Override
//    public final int getColumnSize() {
//        return this.szCols;
//    }
    
    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDataColumnsFactory#getColumnType()
     */
    @Override
    public final DpSupportedType getColumnType() {
        return this.enmColType;
    }
    
    /**
     * <p>
     * Creates a new collection of data columns according to the configuration record supplied at
     * construction.
     * </p>
     * <p>
     * Returned object is an immutable array list (i.e., a "vector") created from Java streams.
     * The columns are ordered according to the ordering of the column name <code>Set</code>
     * provided at creation/construction.  The values within each column are generated by the
     * data factory <code>{@link IDatumFactory}</code> provided at creation/construction.
     * </p>
     * 
     * @param   szCols  the size of all data columns returned (i.e., the number of rows)
     * 
     * @return  vector of data columns containing simulated data
     * 
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDataColumnsFactory#build()
     */
    @Override
    public ArrayList<IDataColumn<Object>> build(int szCols) {

        // Create (immutable) list of columns
        ArrayList<IDataColumn<Object>>   lstCols = this.setColNms
                .stream()
                .<IDataColumn<Object>>map(name -> this.buildColumn(name, szCols))
                .collect(
                        ArrayList::new, 
                        (vec, col) -> vec.add(col), 
                        (vec1, vec2) -> vec1.addAll(vec2)
                        );
        
        return lstCols;
    }
    
    
    //
    // Support Methods
    //
    
    /**
     * <p>
     * Creates a new data column with the given name and appropriate size.
     * </p>
     * <p>
     * The attribute <code>{@link #facValues}</code> is used to create the new values for
     * the data column.  The type parameter for the new column is given by <code>{@link #enmDataType}</code>
     * and the size of the column (i.e., number of rows) is given by <code>{@link #szCols}</code>.
     * </p>
     * <p>
     * Currently the concrete type of the returned interface is given by <code>{@link StaticDataColumn}</code>.
     * This class is provided in the Java API client library.
     * </p>
     * 
     * @param strName   data column name
     * @param szCols    the size of the data column returned (i.e., the number of rows)
     * 
     * @return  new, populated implementation of the <code>IDataColumn</code> interface.
     */
    private IDataColumn<Object> buildColumn(String strName, int szCols) {
        
        // Create the value vector container and pack it with new values
        ArrayList<Object>   vecVals = new ArrayList<>(szCols);
        for (int i=0; i<szCols; i++) {
            Object objVal = this.facValues.nextDatum();
            
            vecVals.add(objVal);
        }
        
        // Create the new column
        StaticDataColumn<Object>    col = StaticDataColumn.from(strName, this.enmColType, vecVals);
        
        return col;
    }
    
}
