/*
 * Project: dp-jal
 * File:	FrameTimestampsFactory.java
 * Package: com.ospreydcs.dp.jal.tools.common.datagen.factories.frames
 * Type: 	FrameTimestampsFactory
 *
 * Copyright 2010-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * @author Christopher K. Allen
 * @org    OspreyDCS
 * @since Dec 30, 2025
 *
 */
package com.ospreydcs.dp.jal.tools.common.datagen.factories.frames;

import java.time.DateTimeException;
import java.time.Duration;
import java.time.Instant;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;

import com.ospreydcs.dp.jal.common.DpTimestampCase;
import com.ospreydcs.dp.jal.common.UniformSamplingClock;
import com.ospreydcs.dp.jal.ingest.IngestionFrame;
import com.ospreydcs.dp.jal.tools.common.datagen.IFrameTimestampsFactory;
import com.ospreydcs.dp.jal.tools.config.JalToolsConfig;
import com.ospreydcs.dp.jal.tools.config.datagen.frames.JalToolsFramesTmsConfig;

/**
 * <p>
 * Factory class for simulated timestamp generation used in ingestion frame factories.
 * </p>
 * <p>
 * The timestamps generated by this class are always uniform.  That is, whether a sampling clock
 * or an explicit timestamp list is generated, all timestamps are equally spaced.  The timestamp
 * spacing is determined by the sampled period provided at construction.
 * </p>
 * <p>
 * <h2>Timestamp Types</h2>
 * There are 2 ingestion frame timestamp "types" supported by the Data Platform.  These types are 
 * enumerated in the enumeration <code>{@link DpTimestampCase}</code>:
 * <ol>
 * <li><code>{@link DpTimestampCase#SAMPLING_CLOCK}</code> - timestamps are generated by a uniform sampling clock,</li>
 * <li><code>{@link DpTimestampCase#TIMESTAMP_LIST}</code> - timestamps are contained in an explicit (ordered) list.</li>
 * </ol>
 * The actual ingestion frame timestamps are generated by choice of methods <code>{@link #nextUniformClock(Instant)}</code>
 * and <code>{@link #nextTimestampVector(Instant)}</code>.  The number of timestamps produced by the latter method
 * is determined by the sample count.
 * Note that explict timestamp lists are more expensive than uniform sampling clocks as they require more resources and
 * processing time.
 * </p>
 * <p>
 * <h2>Sample Period</h2>
 * Although explicit timestamp lists are supported by the Data Platform and can have arbitrary spacing within an
 * ingestion frame, this frame timestamp factory always produces uniformly generated timestamps.  The spacing
 * (i.e., time interval) between timestamps is given by the sampling period provided at construction/creation.
 * Note that the sampling frequency is the inverse of the sampling period.
 * <p>
 * <h2>Sample Count</h2>
 * The number timestamps for each ingestion frame is determined by the sample count provided at construction/creation.
 * The sample count is immutable and all invocations of <code>{@link #nextUniformClock(Instant)}</code> and
 * <code>{@link #nextTimestampVector(Instant)}</code> always produce the same number of timestamps.
 * The value returned by <code>{@link #nextFrameStart(Instant)}</code> is determined by the sample count and the 
 * sample period.
 * </p>
 *
 * @author Christopher K. Allen
 * @since Dec 30, 2025
 *
 */
public class FrameTimestampsFactory implements IFrameTimestampsFactory {

    
    //
    // Creators
    //
    
    /**
     * <p>
     * Creates and returns a new <code>FrameTimestampsFactory</code> instance configured with all default arguments.
     * </p>
     * <p>
     * This creator uses default values for all configuration parameters.  Default values are taken from the
     * JAL Tools default configuration and assigned as class constants.  We have the following:
     * <ul>
     * <li><code>cntSmpls = {@link #INT_SMPLS_DEF}</code>.</li>
     * <li><code>durPeriod = {@link #DUR_PERIOD_DEF}</code>.</li>
     * <li><code>insStart = {@link #INS_START_DEF}</code>.</li>
     * <li><code>enmTmsCase = {@link #ENM_TMS_CASE_DEF}</code>.</li>
     * <li><code>durDelay = {@link #DUR_DELAY_DEF}</code>.</li>
     * </ul>
     * </p>
     * 
     * @return  a new <code>FrameTimestampsFactory</code> instance ready for ingestion frame timestamp generation
     */
    public static FrameTimestampsFactory    from() {
        return FrameTimestampsFactory.from(INT_SMPLS_DEF);
    }
    
    /**
     * <p>
     * Creates and returns a new <code>FrameTimestampsFactory</code> instance configured with the given arguments.
     * </p>
     * <p>
     * This creator uses default values for some configuration parameters.  Default values are taken from the
     * JAL Tools default configuration and assigned as class constants.  We have the following:
     * <ul>
     * <li><code>durPeriod = {@link #DUR_PERIOD_DEF}</code>.</li>
     * <li><code>insStart = {@link #INS_START_DEF}</code>.</li>
     * <li><code>enmTmsCase = {@link #ENM_TMS_CASE_DEF}</code>.</li>
     * <li><code>durDelay = {@link #DUR_DELAY_DEF}</code>.</li>
     * </ul>
     * </p>
     * 
     * @param cntSmpls  number of samples (timestamps) per ingestion frame
     * 
     * @return  a new <code>FrameTimestampsFactory</code> instance ready for ingestion frame timestamp generation
     */
    public static FrameTimestampsFactory    from(int cntSmpls) {
        return FrameTimestampsFactory.from(cntSmpls, DUR_PERIOD_DEF);
    }
    
    /**
     * <p>
     * Creates and returns a new <code>FrameTimestampsFactory</code> instance configured with the given arguments.
     * </p>
     * <p>
     * This creator uses default values for some configuration parameters.  Default values are taken from the
     * JAL Tools default configuration and assigned as class constants.  We have the following:
     * <ul>
     * <li><code>insStart = {@link #INS_START_DEF}</code>.</li>
     * <li><code>enmTmsCase = {@link #ENM_TMS_CASE_DEF}</code>.</li>
     * <li><code>durDelay = {@link #DUR_DELAY_DEF}</code>.</li>
     * </ul>
     * </p>
     * 
     * @param cntSmpls  number of samples (timestamps) per ingestion frame
     * @param durPeriod the (uniform) sampling period
     * 
     * @return  a new <code>FrameTimestampsFactory</code> instance ready for ingestion frame timestamp generation
     */
    public static FrameTimestampsFactory    from(int cntSmpls, Duration durPeriod) {
        return FrameTimestampsFactory.from(cntSmpls, durPeriod, INS_START_DEF);
    }
    
    /**
     * <p>
     * Creates and returns a new <code>FrameTimestampsFactory</code> instance configured with the given arguments.
     * </p>
     * <p>
     * This creator uses default values for some configuration parameters.  Default values are taken from the
     * JAL Tools default configuration and assigned as class constants.  We have the following:
     * <ul>
     * <li><code>enmTmsCase = {@link #ENM_TMS_CASE_DEF}</code>.</li>
     * <li><code>durDelay = {@link #DUR_DELAY_DEF}</code>.</li>
     * </ul>
     * </p>
     * 
     * @param cntSmpls  number of samples (timestamps) per ingestion frame
     * @param durPeriod the (uniform) sampling period
     * @param insStart  the start time for the sampling process (i.e., the 1st timestamp in the 1st frame)
     * 
     * @return  a new <code>FrameTimestampsFactory</code> instance ready for ingestion frame timestamp generation
     */
    public static FrameTimestampsFactory    from(int cntSmpls, Duration durPeriod, Instant insStart) {
        return FrameTimestampsFactory.from(cntSmpls, durPeriod, insStart, ENM_TMS_CASE_DEF);
    }
    
    /**
     * <p>
     * Creates and returns a new <code>FrameTimestampsFactory</code> instance configured with the given arguments.
     * </p>
     * <p>
     * This creator uses default values for some configuration parameters.  Default values are taken from the
     * JAL Tools default configuration and assigned as class constants.  We have the following:
     * <ul>
     * <li><code>durDelay = {@link #DUR_DELAY_DEF}</code>.</li>
     * </ul>
     * </p>
     * 
     * @param cntSmpls  number of samples (timestamps) per ingestion frame
     * @param durPeriod the (uniform) sampling period
     * @param insStart  the start time for the sampling process (i.e., the 1st timestamp in the 1st frame)
     * @param enmCase   the preferred timestamp case
     * 
     * @return  a new <code>FrameTimestampsFactory</code> instance ready for ingestion frame timestamp generation
     */
    public static FrameTimestampsFactory from(int cntSmpls, Duration durPeriod, Instant insStart, DpTimestampCase enmCase) {
        return FrameTimestampsFactory.from(cntSmpls, durPeriod, insStart, enmCase, DUR_DELAY_DEF);
    }
    
    /**
     * <p>
     * Creates and returns a new <code>FrameTimestampsFactory</code> instance configured with the given arguments.
     * </p>
     * <p>
     * This creator is equivalent to the canonical constructor 
     * <code>{@link #FrameTimestampsFactory(DpTimestampCase, int, Duration, Instant, Duration)}</code> containing
     * all required configuration parameters.
     * </p>
     * 
     * @param cntSmpls  number of samples (timestamps) per ingestion frame
     * @param durPeriod the (uniform) sampling period
     * @param insStart  the start time for the sampling process (i.e., the 1st timestamp in the 1st frame)
     * @param enmCase   the preferred timestamp case
     * @param durDelay  optional sampling delay added to the start time
     * 
     * @return  a new <code>FrameTimestampsFactory</code> instance ready for ingestion frame timestamp generation
     */
    public static FrameTimestampsFactory from(int cntSmpls, Duration durPeriod, Instant insStart, DpTimestampCase enmCase, Duration durDelay) {
        return new FrameTimestampsFactory(cntSmpls, durPeriod, insStart, enmCase, durDelay);
    }

    /**
     * <p>
     * Parses the collection of arguments as values of the <code>FrameTimestampFactory</code> construction argument values.
     * </p>
     * <p>
     * The element strings of the argument array are parsed as formatted, string values of the record
     * field.  Typically, the argument is part of a application command-line argument collection.
     * There, the argument array elements follow a command-line (delimiting) variable, say '<code>--tms</code>'.
     * Assuming as such, the format of the argument array elements is as follows:
     * <code>
     * <pre>
     * > java application --tms [samples [period [start [type [delay]]]]] ... 
     * </pre>
     * </code>
     * where '<code>application</code> is the example application name and the brackets indicate optional
     * inclusion.
     * The strings following the variable <code>--tms</code> are the field values parsed here, in order.
     * <ol>
     * <li>'samples' &rarr; <code>{@link #cntSamples()}</code> [default <code>{@link #CNT_SMPLS_DEF}</code>],
     * <li>'period' &rarr; <code>{@link #durPeriod()}</code> [default <code>{@link #DUR_PERIOD_DEF}</code>],
     * <li>'start' &rarr; <code>{@link #insStart()}</code> [default <code>{@link #INS_START_DEF}</code>],
     * <li>'type' &rarr; <code>{@link #enmType()}</code> [default <code>{@link #ENM_TMS_CASE_DEF}</code>],
     * <li>'delay' &rarr; <code>{@link #durDelay()}</code> [default <code>{@link #DUR_DELAY_DEF}</code>],
     * </ol>
     * </p>
     * <p>
     * <h2>NOTES:</h2>
     * <ul>
     * <li>
     * If values do not appear in the argument array the fields values are populated with JAL Tools 
     * default configuration values, which are captured as the record constant indicated above.
     * </li>
     * <li>
     * The ordering of the above string values is strict.  One cannot skip field values as default then supply
     * a later value.  For example, in order to specify the delay parameter 'delay' 
     * (i.e., <code>{@link #durDelay()}</code> all other parameters must be supplied.
     * </li>
     * </ul>  
     * </p>
     * 
     * @param args  ordered collection of field values of format [samples [type [period [start [delay]]]]]
     * 
     * @return  a new <code>TimestampFactorySpec</code> record populated with the parsed argument strings
     * 
     * @throws NumberFormatException    invalid numeric format for 'samples'
     * @throws TypeNotPresentException  invalid <code>{@link DpTimestampCase}</code> constant for 'type'  
     * @throws DateTimeParseException   invalid ISO-8605 date/time/duration format for 'period', 'start', or 'delay' 
     */
    public static FrameTimestampsFactory parse(String...args) throws NumberFormatException, TypeNotPresentException, DateTimeParseException {

        // If the argument collection is empty return the default configuration
        if (args.length < 1)
            return FrameTimestampsFactory.from();

        int     indArg = 0;
        
        // Get the number of samples
        String  strCntSamples   = args[indArg++];
        int     cntSamples = Integer.valueOf(strCntSamples);    // throws NumberFormatException
        if (args.length < (indArg+1))
            return FrameTimestampsFactory.from(cntSamples);
        
        // Get the period within the argument list
        String      strPeriod = args[indArg++];
        Duration    durPeriod = Duration.parse(strPeriod);  // DateTimeParseException
        if (args.length < (indArg+1))
            return FrameTimestampsFactory.from(cntSamples, durPeriod);
        
        // Get the start instant from the argument list
        String      strStart = args[indArg++];
        Instant     insStart = Instant.parse(strStart);     // throws DateTimeParseException
        if (args.length < (indArg+1))
            return FrameTimestampsFactory.from(cntSamples, durPeriod, insStart);
        
        // Get the timestamp type within the arguments list
        String  strTmsType = args[indArg++];
        DpTimestampCase enmType = DpTimestampCase.valueFrom(strTmsType);  // throws TypeNotPresentException
        if (args.length < (indArg+1))
            return FrameTimestampsFactory.from(cntSamples, durPeriod, insStart, enmType);
        
        // Get the start delay from the argument collection
        String      strDelay = args[indArg++];
        Duration    durDelay = Duration.parse(strDelay);    // throws DateTimeParseException
        return FrameTimestampsFactory.from(cntSamples, durPeriod, insStart, enmType, durDelay);
    }    
    
    /**
     * <p>
     * Retrieves and returns the default ingestion frame timestamp configuration for the default 
     * ingestion frame factory configuration.
     * </p>
     * <p>
     * The JAL Tools default configuration contains a default ingestion frame configuration.  This configuration is
     * used by ingestion frame factories to create <code>{@link IngestionFrame}</code> instances when no explicit
     * configuration is given.
     * </p>
     * The returned <code>FrameTimestampsFactory</code> instance specifies the timestamps in the 
     * default ingestion frame.  The data column specifications for the default ingestion frame can be
     * obtained from the <code>{@link FrameColumnsFactory#defaultFrame()}</code> method.  
     * </p>
     * <p>
     * The method retrieves the default timestamps specifications contained in the <code>{@link JalToolsFramesTmsConfig}</code>
     * structure class list within the <code>{@link JalToolsConfig}</code> default configuration.  The parameters
     * for the timestamp specification are extracted and a new <code>FrameTimestampsFactory</code> instance is created.
     * </p>
     * @apiNote
     * This method is essentially equivalent to the creator <code>{@link #from()}</code> which uses all default 
     * parameters for timestamp factory configuration.
     * 
     * @return  a new <code>FrameTimestampsFactory</code> instance as specified in the JAL Tools default configuration
     */
    public static FrameTimestampsFactory    defaultFrame() {
        return FrameTimestampsFactory.from();
    }
    
    //
    // JAL Tools Resources
    //
    
    /** The frame timestamps default configuration */
    private static final    JalToolsFramesTmsConfig     CFG_DEF = JalToolsConfig.getInstance().datagen.frames.timestamps;
    
    
    //
    // Class Constants
    //
    
    /** The default sample count */
    public static final     int                         INT_SMPLS_DEF = CFG_DEF.count;
    
    /** The default sample period */
    public static final     Duration                    DUR_PERIOD_DEF = CFG_DEF.periodDuration();
    
    /** The default start time */
    public static final     Instant                     INS_START_DEF = CFG_DEF.startInstant();

    
    /** The default preferred timestamp case */
    public static final     DpTimestampCase             ENM_TMS_CASE_DEF = CFG_DEF.type;
    
    /** The default start delay */
    public static final     Duration                    DUR_DELAY_DEF = CFG_DEF.delayDuration();
    
    
    //
    // Defining Attributes
    //
    
    /** The sample count */
    private final int                   cntSmpls;
    
    /** The sample period */
    private final Duration              durPeriod;
    
    /** The start time instant */
    private final Instant               insStart;

    
    /** The preferred timestamp case */
    private final DpTimestampCase       enmCase;
    
    /** The start time delay */
    private final Duration              durDelay;
    
    
    //
    // State Variables
    //
    
    /** The current ingestion frame timestamp start instant */
    private Instant     insTmsCurr;
    
    
    //
    // Constructors
    //
    
    /**
     * <p>
     * Constructs a new <code>FrameTimestampsFactory</code> instance.
     * </p>
     *
     * @param cntSmpls  number of samples (timestamps) per ingestion frame
     * @param durPeriod the (uniform) sampling period
     * @param insStart  the start time for the sampling process (i.e., the 1st timestamp in the 1st frame)
     * @param enmCase   the preferred timestamp case
     * @param durDelay  optional sampling delay added to the start time
     */
    public FrameTimestampsFactory(int cntSmpls, Duration durPeriod, Instant insStart, DpTimestampCase enmCase, Duration durDelay) {
        this.cntSmpls = cntSmpls;
        this.durPeriod = durPeriod;
        this.insStart = insStart;
        
        this.enmCase = enmCase;
        this.durDelay = durDelay;
        
        this.insTmsCurr = this.insStart.plus(this.durDelay);
    }

    
    //
    // IFrameTimestampsFactory Interface
    //
    
    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IFrameTimestampsFactory#getSampleCount()
     */
    @Override
    public int getSampleCount() {
        return this.cntSmpls;
    }

    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IFrameTimestampsFactory#getTimestampCase()
     */
    @Override
    public DpTimestampCase getTimestampCase() {
        return this.enmCase;
    }

//    /**
//     * @see com.ospreydcs.dp.jal.tools.common.datagen.IFrameTimestampsFactory#getStartInstant()
//     */
//    @Override
//    public Instant getStartInstant() throws DateTimeException, ArithmeticException {
//        // TODO Auto-generated method stub
//        return null;
//    }

    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IFrameTimestampsFactory#nextFrameStart(java.time.Instant)
     */
    @Override
    public Instant nextFrameStart() throws DateTimeException, ArithmeticException {
        return this.insStart;
    }

    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IFrameTimestampsFactory#nextUniformClock(java.time.Instant)
     */
    @Override
    public UniformSamplingClock nextUniformClock() throws IllegalArgumentException {
        
        UniformSamplingClock clk = UniformSamplingClock.from(this.insTmsCurr, this.cntSmpls, this.durPeriod);
        
        this.insTmsCurr = this.advanceFrameStart(this.insTmsCurr);
        
        return clk;
    }

    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IFrameTimestampsFactory#nextTimestampVector(java.time.Instant)
     */
    @Override
    public ArrayList<Instant> nextTimestampVector() throws DateTimeException, ArithmeticException {
        
        ArrayList<Instant>   vecTms = new ArrayList<>(this.cntSmpls);
        
        for (int iTms=0; iTms<this.cntSmpls; iTms++) {
            vecTms.add(insTmsCurr);
            
            insTmsCurr = insTmsCurr.plus(this.durPeriod);     // throws DateTimeException, ArithmeticException
        }
        
        return vecTms;
    }

    
    // 
    // Object Overrides
    //
    
    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {

        if (obj instanceof FrameTimestampsFactory fac) {
            boolean bolResult = (this.cntSmpls == fac.cntSmpls)
                    && (this.durPeriod.equals(fac.durPeriod))
                    && (this.insStart.equals(fac.insStart))
                    && (this.enmCase == fac.enmCase)
                    && (this.durDelay.equals(fac.durDelay));
            
            return bolResult;
        }
        
        return false;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder   buf = new StringBuilder();
        
        buf.append("IFrameTimestampFactory Implementation : " + this.getClass().getName() + "\n");
        buf.append("Sample count           : " + this.cntSmpls + "\n");
        buf.append("Sampling period        : " + this.durPeriod + "\n");
        buf.append("Sampling start instant : " + this.insStart + "\n");
        buf.append("Sampling start delay   : " + this.durDelay + "\n");
        buf.append("Timestamp case         : " + this.enmCase + "\n");
        
        return buf.toString();
    }

    
    // 
    // Support Methods
    //
    
    /**
     * <p>
     * Advances the current frame starting time instant according to the period and the sampling count.
     * </p>
     * <p>
     * The returned value is the start time for the next sequence of timestamps generated by either
     * <code>{@link #nextUniformClock()}</code> or <code>{@link #nextTimestampVector()}</code>.  Specifically,
     * if <i>t<sub>n</sub></i> is the start time instant for ingestion frame <i>n</i> then the method
     * returns <i>t</i><sub><i>n</i>+1</sub> given by
     * <pre>
     *   <i>t</i><sub><i>n</i>+1</sub> = <i>t<sub>n</sub></i> + <i>NT</i>
     * </pre>
     * where
     * <ul>
     * <li><i>N</i> = sample count,</li>
     * <li><i>T</i> = sample period.</li>
     * </ul>
     * </p> 
     * 
     * @param insTmsCurr    the current frame start time instant <i>t<sub>n</sub></i>
     *  
     * @return  the next frame start time instant <i>t</i><sub><i>n</i>+1</sub>
     * 
     * @throws DateTimeException    internal <code>Instant</code> addition failed
     * @throws ArithmeticException  numeric overflow occurred in <code>Instant</code> addition 
     */
    private Instant advanceFrameStart(Instant insTmsCurr) throws ArithmeticException, DateTimeException {
        
        Duration    durRange = this.durPeriod.multipliedBy(this.cntSmpls);    // throws ArithmeticException
        Instant     insTmsNext = insTmsCurr.plus(durRange);      // throws DateTimeException, ArithmeticException
        
        return insTmsNext;
    }
}
