/*
 * Project: dp-jal
 * File:	FrameColumnsFactory.java
 * Package: com.ospreydcs.dp.jal.tools.common.datagen.factories.frames
 * Type: 	FrameColumnsFactory
 *
 * Copyright 2010-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * @author Christopher K. Allen
 * @org    OspreyDCS
 * @since Nov 18, 2025
 *
 */
package com.ospreydcs.dp.jal.tools.common.datagen.factories.frames;

import java.lang.reflect.MalformedParametersException;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.MissingResourceException;
import java.util.NoSuchElementException;
import java.util.Set;
import java.util.TreeSet;
import java.util.stream.IntStream;

import javax.naming.ConfigurationException;

import com.ospreydcs.dp.jal.common.DpSupportedType;
import com.ospreydcs.dp.jal.common.IDataColumn;
import com.ospreydcs.dp.jal.ingest.IngestionFrame;
import com.ospreydcs.dp.jal.model.table.StaticDataColumn;
import com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory;
import com.ospreydcs.dp.jal.tools.common.datagen.IFrameColumnsFactory;
import com.ospreydcs.dp.jal.tools.common.datagen.JalComplexType;
import com.ospreydcs.dp.jal.tools.common.datagen.factories.values.ByteArrayFactory;
import com.ospreydcs.dp.jal.tools.common.datagen.factories.values.ImageFactory;
import com.ospreydcs.dp.jal.tools.common.datagen.factories.values.ScalarFactory;
import com.ospreydcs.dp.jal.tools.common.datagen.factories.values.StructureFactory;
import com.ospreydcs.dp.jal.tools.common.datagen.factories.values.TensorFactory;
import com.ospreydcs.dp.jal.tools.common.datagen.factories.values.TimestampFactory;
import com.ospreydcs.dp.jal.tools.config.JalToolsConfig;
import com.ospreydcs.dp.jal.tools.config.datagen.cols.JalToolsColumnsConfig;
import com.ospreydcs.dp.jal.tools.config.datagen.frames.JalToolsFramesConfig;
import com.ospreydcs.dp.jal.util.JavaRuntime;

/**
 * <p>
 * Factory class for simultaneous generation of multiple columns of simulated data.
 * </p>
 * <p>
 * This class is provided in addition to class <code>DataColumnFactory</code>, which creates single columns
 * at a time.  This class is capable of simultaneously generating multiple columns of <code>IDataColumn</code>
 * instances per <code>{@link #build()}</code> invocation.
 * </p>
 * <p>
 * Instances of this class are used primarily for column generation within ingestion frame factory class
 * instances.  This column factory creates multiple columns upon invocation of the <code>{@link #build()}</code>
 * method.  All data columns contain simulated data of the same data type, specifically, the data type
 * generated by the <code>{@link IDatumFactory}</code> instance provided at creation/construction. 
 * </p>
 * <p>
 * <h2>Column Generation</h2>
 * The <code>{@link #build()}</code> method is used to create vectors (i.e., <code>{@link ArrayList}</code>) of
 * <code>IDataColumn</code> objects according to the <code>FrameColumnsFactory</code> configuration determined
 * at creation/construction.  The number of columns returned in the vector is given by the size of the
 * <code>{@link Set}</code> argument containing column names, while the type of each column data value is
 * given by <code>{@link IDatumFactory#getDatumType()}</code> of the data factory provided at creation/construction.  
 * Column values are generated using the <code>{@link IDatumFactory}</code> by sequential invocation of
 * <code>{@link IDatumFactory#nextDatum()}</code>.
 * </p>
 * <h2>Column Types</h2>
 * The data columns returned by the <code>{@link #build()}</code> method are implementations of the interface
 * <code>{@link IDataColumn}</code>.  Currently, the underlying implementation is of type
 * <code>{@link StaticDataColumn}</code>.
 * </p>
 * <p>
 * <h2>Column Count</h2>
 * The number of columns created in each invocation to <code>{@link #build()}</code> is the size of the set
 * of column names provided at creation/construction.
 * </p>
 * <p>
 * <h2>Datum Factories</h2>
 * Datum factories are classes exposing the <code>{@link IDatumFactory}</code> interface.  
 * The template parameter <code>{@link FactorySpec}</code> identifies the type and configuration for the
 * datum factory producing the simulated column data.  Again, the type parameters must be consistent with the
 * <code>{@link #enmType()}</code> field.  The inclusion of both the type parameter and the datum type field
 * is necessary for the parsing operation <code>{@link #parse(String...)}</code> available for parsing application
 * command-line arguments.
 * </p>  
 * <p>
 * When parsing command-line arguments the datum factory specification is identified by 
 * <code>{@link JalComplexType}</code> enumeration constant.
 * The supported datum factories associations are given by the following: 
 * <ul>
 * <li><code>{@link JalComplexType#SCALAR} &rarr; {@link ScalarFactory}</code>.</li>
 * <li><code>{@link JalComplexType#BYTES} &rarr; {@link ByteArrayFactory}</code>.</li>
 * <li><code>{@link JalComplexType#TIMESTAMP} &rarr; {@link TimestampFactory}</code>.</li>
 * <li><code>{@link JalComplexType#IMAGE} &rarr; {@link ImageFactory}</code>.</li>
 * <li><code>{@link JalComplexType#TENSOR} &rarr; {@link TensorFactory}</code>.</li>
 * <li><code>{@link JalComplexType#STRUCTURE} &rarr; {@link StructureFactory}.</code></li>
 * </ul>
 * </p>
 * 
 *
 * @author Christopher K. Allen
 * @since Nov 18, 2025
 *
 */
public class FrameColumnsFactory implements IFrameColumnsFactory<Object> {

    
    //
    // Creators
    //
    
    /**
     * <p>
     * Convenience Creator: 
     * Creates a new <code>FrameColumnsFactory</code> instance populated from all default configuration parameters.
     * </p>
     * <p>
     * The returned frame columns factory is configured completely with the default configuration parameters
     * taken from the JAL Tools default configuration.
     * </p>
     * <p>
     * <h2>Default Parameters</h2>
     * <b>WARNING:</b>. This method uses default parameters from the JAL Tools default configuration  
     * and infers the values of some configuration parameters.  Configuration parameters not provided 
     * are populated as follows:
     * <ul>
     * <li>column count &rarr; <code>{@link #INT_COL_CNT_DEF}</code>.</li>
     * <li>data column name prefix &rarr; <code>{@link #STR_NM_PREF_DEF}</code>. </li>
     * <li><code>{@link IDatumFactory} &rarr; {@link #parseDatumFactory(JalComplexType, String...)}</code> with:
     *     <ul>
     *     <li><code>{@link JalComplexType} = {@link #ENM_COL_TYPE_DEF}</code>,</li>
     *     <li><code>{@link String[]} = {@link #ARR_FAC_SPEC_DEF}</code>.</li>
     *     </ul>
     * </li>
     * </ul>
     * </p>
     * @apiNote
     * This creator produces frame column factories with the default column configuration as specified
     * in the JAL Tools default configuration.  Note that the default ingestion frame column is different
     * from the default ingestion frame <em>columns</em>.  Thus, this creator is <b>not</b> equivalent
     * to creator <code>{@link #defaultFrame()}</code>, which returns all column specifications for the
     * default ingestion frame.
     *  
     * @return  a new <code>FrameColumnsFactory</code> instance ready for data column generation
     * 
     * @throws IllegalArgumentException     either non-positive column count or value factory is <code>null</code>
     * @throws TypeNotPresentException      unknown <code>JalScalarType</code> enumeration constant (scalar factory)
     * @throws NumberFormatException        invalid numeric format (e.g., scalar factory bad 'numIncr' or 'lngSeed') 
     * @throws UnsupportedOperationException unable to create 'numIncr' field for numeric value type (scalar factory)
     * @throws MissingResourceException      timestamp factory had empty arguments
     * @throws DateTimeParseException        bad ISO-8601 time and/or duration format (e.g., timestamp factory period, start, etc.) 
     * @throws ConfigurationException        the tensor shape was invalid (e.g., an axis size could not be parsed, non-positive axis size, etc.)
     * @throws NoSuchElementException        unrecognized <code>{@link JalComplexType}</code> constant in argument  
     */
    public static FrameColumnsFactory   from() throws IllegalArgumentException, TypeNotPresentException, NumberFormatException, UnsupportedOperationException, MissingResourceException, DateTimeParseException, ConfigurationException, NoSuchElementException {
        
        return FrameColumnsFactory.from(INT_COL_CNT_DEF);
    }
        
    /**
     * <p>
     * Convenience Creator: 
     * Creates a new <code>FrameColumnsFactory</code> instance populated from the available argument values.
     * </p>
     * <p>
     * The returned frame columns factory is configured either directory or inferred, with the argument values.
     * </p>
     * <p>
     * <h2>Default Parameters</h2>
     * <b>WARNING:</b>. This method uses default parameters from the JAL Tools default configuration  
     * and infers the values of some configuration parameters.  Configuration parameters not provided 
     * are populated as follows:
     * <ul>
     * <li>data column name prefix &rarr; <code>{@link #STR_NM_PREF_DEF}</code>. </li>
     * <li><code>{@link IDatumFactory} &rarr; {@link #parseDatumFactory(JalComplexType, String...)}</code> with:
     *     <ul>
     *     <li><code>{@link JalComplexType} = {@link #ENM_COL_TYPE_DEF}</code>,</li>
     *     <li><code>{@link String[]} = {@link #ARR_FAC_SPEC_DEF}</code>.</li>
     *     </ul>
     * </li>
     * </ul>
     * </p>
     *  
     * @param intCols       number of data columns produced by factory
     * 
     * @return  a new <code>FrameColumnsFactory</code> instance ready for data column generation
     * 
     * @throws IllegalArgumentException     either non-positive column count or value factory is <code>null</code>
     * @throws TypeNotPresentException      unknown <code>JalScalarType</code> enumeration constant (scalar factory)
     * @throws NumberFormatException        invalid numeric format (e.g., scalar factory bad 'numIncr' or 'lngSeed') 
     * @throws UnsupportedOperationException unable to create 'numIncr' field for numeric value type (scalar factory)
     * @throws MissingResourceException      timestamp factory had empty arguments
     * @throws DateTimeParseException        bad ISO-8601 time and/or duration format (e.g., timestamp factory period, start, etc.) 
     * @throws ConfigurationException        the tensor shape was invalid (e.g., an axis size could not be parsed, non-positive axis size, etc.)
     * @throws NoSuchElementException        unrecognized <code>{@link JalComplexType}</code> constant in argument  
     */
    public static FrameColumnsFactory   from(int intCols) throws IllegalArgumentException, TypeNotPresentException, NumberFormatException, UnsupportedOperationException, MissingResourceException, DateTimeParseException, ConfigurationException, NoSuchElementException {
        
        return FrameColumnsFactory.from(intCols, STR_NM_PREF_DEF);
    }
        
    /**
     * <p>
     * Convenience Creator: 
     * Creates a new <code>FrameColumnsFactory</code> instance populated from the available argument values.
     * </p>
     * <p>
     * The returned frame columns factory is configured either directory or inferred, with the argument values.
     * </p>
     * <p>
     * <h2>Default Parameters</h2>
     * <b>WARNING:</b>. This method uses default parameters from the JAL Tools default configuration  
     * and infers the values of some configuration parameters.  Configuration parameters not provided 
     * are populated as follows:
     * <ul>
     * <li><code>{@link IDatumFactory} &rarr; {@link #parseDatumFactory(JalComplexType, String...)}</code> with:
     *     <ul>
     *     <li><code>{@link JalComplexType} = {@link #ENM_COL_TYPE_DEF}</code>,</li>
     *     <li><code>{@link String[]} = {@link #ARR_FAC_SPEC_DEF}</code>.</li>
     *     </ul>
     * </li>
     * </ul>
     * </p>
     *  
     * @param intCols       number of data columns produced by factory
     * @param strNmPref     prefix for data column names produced by factory
     * 
     * @return  a new <code>FrameColumnsFactory</code> instance ready for data column generation
     * 
     * @throws IllegalArgumentException     either non-positive column count or value factory is <code>null</code>
     * @throws TypeNotPresentException      unknown <code>JalScalarType</code> enumeration constant (scalar factory)
     * @throws NumberFormatException        invalid numeric format (e.g., scalar factory bad 'numIncr' or 'lngSeed') 
     * @throws UnsupportedOperationException unable to create 'numIncr' field for numeric value type (scalar factory)
     * @throws MissingResourceException      timestamp factory had empty arguments
     * @throws DateTimeParseException        bad ISO-8601 time and/or duration format (e.g., timestamp factory period, start, etc.) 
     * @throws ConfigurationException        the tensor shape was invalid (e.g., an axis size could not be parsed, non-positive axis size, etc.)
     * @throws NoSuchElementException        unrecognized <code>{@link JalComplexType}</code> constant in argument  
     */
    public static FrameColumnsFactory   from(int intCols, String strNmPref) throws IllegalArgumentException, TypeNotPresentException, NumberFormatException, UnsupportedOperationException, MissingResourceException, DateTimeParseException, ConfigurationException, NoSuchElementException {
        
        // Create the default ingestion frame datum factory
        IDatumFactory   facValues = FrameColumnsFactory.parseDatumFactory(ENM_COL_TYPE_DEF, ARR_FAC_SPEC_DEF);  // throws all exceptions except IllegalArgumentException
        
        return FrameColumnsFactory.from(intCols, strNmPref, facValues);     // throws IllegalArgumentException
    }
    
    /**
     * <p>
     * Convenience Creator: 
     * Creates a new <code>FrameColumnsFactory</code> instance populated from the available argument values.
     * </p>
     * <p>
     * The returned frame columns factory is configured either directory or inferred, with the argument values.
     * </p>
     * <p>
     * <h2>Default Parameters</h2>
     * <b>WARNING:</b>. This method uses default parameters from the JAL Tools default configuration  
     * and infers the values of some configuration parameters.  Configuration parameters not provided 
     * are populated as follows:
     * <ul>
     * <li>column count &rarr; <code>{@link #INT_COL_CNT_DEF}</code>.</li>
     * <li>data column name prefix &rarr; <code>{@link #STR_NM_PREF_DEF}</code>. </li>
     * </ul>
     * </p>
     *  
     * @param facValues   the datum factory used for simulated data production
     * 
     * @return  a new <code>FrameColumnsFactory</code> instance ready for data column generation
     * 
     * @throws IllegalArgumentException either non-positive column count or value factory is <code>null</code>
     */
    public static FrameColumnsFactory   from(IDatumFactory facValues) throws IllegalArgumentException {
        
        return FrameColumnsFactory.from(INT_COL_CNT_DEF, facValues);
    }
    
    /**
     * <p>
     * Convenience Creator: 
     * Creates a new <code>FrameColumnsFactory</code> instance populated from the available argument values.
     * </p>
     * <p>
     * The returned frame columns factory is configured either directory or inferred, with the argument values.
     * </p>
     * <p>
     * <h2>Default Parameters</h2>
     * <b>WARNING:</b>. This method uses default parameters from the JAL Tools default configuration  
     * and infers the values of some configuration parameters.  Configuration parameters not provided 
     * are populated as follows:
     * <ul>
     * <li>data column name prefix &rarr; <code>{@link #STR_NM_PREF_DEF}</code>. </li>
     * </ul>
     * </p>
     *  
     * @param intCols     number of data columns produced by factory
     * @param facValues   the datum factory used for simulated data production
     * 
     * @return  a new <code>FrameColumnsFactory</code> instance ready for data column generation
     * 
     * @throws IllegalArgumentException either non-positive column count or value factory is <code>null</code>
     */
    public static FrameColumnsFactory   from(int intCols, IDatumFactory facValues) throws IllegalArgumentException {
        
        return FrameColumnsFactory.from(intCols, STR_NM_PREF_DEF, facValues);
    }
    
    /**
     * <p>
     * Standard Creator: 
     * Creates a new <code>FrameColumnsFactory</code> instance populated from the given argument values.
     * </p>
     * <p>
     * All configuration parameters are populated, either directory or inferred, with the argument values.
     * The column names set for the frame columns factory is created by appending the column index to
     * the argument <code>strNmPref</code>.  
     * </p>
     *  
     * @param intCols       number of data columns produced by factory
     * @param strNmPref     prefix for data column names produced by factory
     * @param facValues     the datum factory instance used for simulated data production
     * 
     * @return  a new <code>FrameColumnsFactory</code> instance ready for data column generation
     * 
     * @throws IllegalArgumentException either non-positive column count or value factory is <code>null</code>
     */
    public static FrameColumnsFactory    from(int intCols, String strNmPref, IDatumFactory facValues) throws IllegalArgumentException {
        Set<String>     setColNms = IntStream.range(0, intCols).mapToObj(i -> strNmPref + Integer.toString(i)).collect(TreeSet::new, TreeSet::add, TreeSet::addAll);
        
        return FrameColumnsFactory.from(setColNms, facValues);  // throws IllegalArgumentException
    }
    
    /**
     * <p>
     * Creates and returns a new <code>FrameColumnsFactory</code> instance configured according to the given arguments.
     * </p>
     * <p>
     * The <code>{@link #build()}</code> method is available for data column creation.  It returns a vector
     * (i.e., <code>{@link ArrayList}</code> of data columns, one for each column name given, containing simulated
     * data produced by the given data value factory.  The size of each column (i.e., the number of rows) is given 
     * by the size argument.
     * See the class documentation on <code>{@link FrameColumnsFactory}</code> for more information.
     * </p>
     * 
     * @param setColNms set of unique column names
     * @param szCols    the size of each data column (i.e., number of rows)
     * @param facValues the data value factory producing simulated column values
     * 
     * @return  a new <code>FrameColumnsFactory</code> instance ready for data column generation
     * 
     * @throws IllegalArgumentException either empty name collection or value factory is <code>null</code>
     * 
     * @see FrameColumnsFactory
     */
    public static final FrameColumnsFactory from(Set<String> setColNms, IDatumFactory facValues) throws IllegalArgumentException {
        return new FrameColumnsFactory(setColNms, facValues);
    }

    /**
     * <p>
     * Convenience Creator: 
     * Creates a new <code>FrameColumnsFactory</code> instance using the argument values and the
     * default creator for the datum factory inferred by the given datum factory type.
     * </p>
     * <p>
     * This is a convenience creator which defers to the default creator for the given 
     * <code>{@link JalComplexType}</code> constant provided.  Specifically, the parameter <code>{@link IDatumeFactory}</code>
     * is populated according to the following assignments:
     * <ul>
     * <li><code>{@link JalComplexType#SCALAR} &rarr; {@link ScalarFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#BYTES} &rarr; {@link ByteArrayFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#TIMESTAMP} &rarr; {@link TimestampFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#IMAGE} &rarr; {@link ImageFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#TENSOR} &rarr; {@link TensorFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#STRUCTURE} &rarr; {@link StructureFactory#from()}.</code></li>
     * </ul>
     * </p>
     * <p>
     * <h2>Default Parameters</h2>
     * <b>WARNING:</b>. This method uses default parameters from the JAL Tools default configuration.  
     * The default parameters are used in the creation of the datum factory specification.  
     * Here the datum factory specification is completely configured to the JAL Tools default state 
     * as specified above.
     * The remaining record fields are populated as follows:
     * <ul>
     * <li>column count &rarr; <code>{@link #INT_COL_CNT_DEF}</code>.</li>
     * <li>column name prefix &rarr; <code>{@link #STR_NM_PREF_DEF}</code>.</li>
     * </ul>
     * </p>
     * 
     * @param enmType       data type of data columns produced by column factory
     * 
     * @return  a new <code>FrameColumnsFactory</code> specification as defined by the available argument values
     * 
     * @throws IllegalArgumentException bad default configuration for datum factory in JAL Tools default configuration   
     * @throws NoSuchElementException   the <code>JalComplexType</code> constant is unsupported
     *
     * @see JalComplexType
     * @see ScalarFactory#from()
     * @see TimestampFactory#from()
     * @see ByteArrayFactory#from()
     * @see ImageFactory#from()
     * @see TensorFactory#from()
     * @see StructureFactory#from()
     */
    public static FrameColumnsFactory   from(JalComplexType enmType) throws IllegalArgumentException, NoSuchElementException {

        return FrameColumnsFactory.from(INT_COL_CNT_DEF, enmType);
    }
    
    /**
     * <p>
     * Convenience Creator: 
     * Creates a new <code>FrameColumnsFactory</code> instance using the argument values and the
     * default creator for the datum factory inferred by the given datum factory type.
     * </p>
     * <p>
     * This is a convenience creator which defers to the default creator for the given 
     * <code>{@link JalComplexType}</code> constant provided.  Specifically, the parameter <code>{@link IDatumeFactory}</code>
     * is populated according to the following assignments:
     * <ul>
     * <li><code>{@link JalComplexType#SCALAR} &rarr; {@link ScalarFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#BYTES} &rarr; {@link ByteArrayFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#TIMESTAMP} &rarr; {@link TimestampFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#IMAGE} &rarr; {@link ImageFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#TENSOR} &rarr; {@link TensorFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#STRUCTURE} &rarr; {@link StructureFactory#from()}.</code></li>
     * </ul>
     * </p>
     * <p>
     * <h2>Default Parameters</h2>
     * <b>WARNING:</b>. This method uses default parameters from the JAL Tools default configuration.  
     * The default parameters are used in the creation of the datum factory specification.  
     * Here the datum factory specification is completely configured to the JAL Tools default state 
     * as specified above.
     * The remaining record fields are populated as follows:
     * <ul>
     * <li>column name prefix &rarr; <code>{@link #STR_NM_PREF_DEF}</code>.</li>
     * </ul>
     * </p>
     * 
     * @param intCols       number of data columns produced by factory
     * @param enmType       data type of data columns produced by column factory
     * 
     * @return  a new <code>FrameColumnsFactory</code> specification as defined by the available argument values
     * 
     * @throws IllegalArgumentException bad default configuration for datum factory in JAL Tools default configuration   
     * @throws NoSuchElementException   the <code>JalComplexType</code> constant is unsupported
     *
     * @see JalComplexType
     * @see ScalarFactory#from()
     * @see TimestampFactory#from()
     * @see ByteArrayFactory#from()
     * @see ImageFactory#from()
     * @see TensorFactory#from()
     * @see StructureFactory#from()
     */
    public static FrameColumnsFactory   from(int intCols, JalComplexType enmType) throws IllegalArgumentException, NoSuchElementException {

        return FrameColumnsFactory.from(intCols, STR_NM_PREF_DEF, enmType);
    }
    
    /**
     * <p>
     * Convenience Creator: 
     * Creates a new <code>FrameColumnsFactory</code> instance using the argument values and the
     * default creator for the datum factory inferred by the given datum factory type.
     * </p>
     * <p>
     * This is a convenience creator which defers to the default creator for the given 
     * <code>{@link JalComplexType}</code> constant provided.  Specifically, the parameter <code>{@link IDatumeFactory}</code>
     * is populated according to the following assignments:
     * <ul>
     * <li><code>{@link JalComplexType#SCALAR} &rarr; {@link ScalarFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#BYTES} &rarr; {@link ByteArrayFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#TIMESTAMP} &rarr; {@link TimestampFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#IMAGE} &rarr; {@link ImageFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#TENSOR} &rarr; {@link TensorFactory#from()}</code>.</li>
     * <li><code>{@link JalComplexType#STRUCTURE} &rarr; {@link StructureFactory#from()}.</code></li>
     * </ul>
     * </p>
     * <p>
     * <h2>Default Parameters</h2>
     * <b>WARNING:</b>. This method uses default parameters from the JAL Tools default configuration.  
     * The default parameters are used in the creation of the datum factory specification.  
     * Here the datum factory specification is completely configured to the JAL Tools default state 
     * as specified above.
     * </p>
     * 
     * @param intCols       number of data columns produced by factory
     * @param strNmPref     prefix for data column names produced by factory
     * @param enmType       data type of data columns produced by column factory
     * 
     * @return  a new <code>FrameColumnsFactory</code> specification as defined by the available argument values
     * 
     * @throws IllegalArgumentException bad default configuration for datum factory in JAL Tools default configuration   
     * @throws NoSuchElementException   the <code>JalComplexType</code> constant is unsupported
     *
     * @see JalComplexType
     * @see ScalarFactory#from()
     * @see TimestampFactory#from()
     * @see ByteArrayFactory#from()
     * @see ImageFactory#from()
     * @see TensorFactory#from()
     * @see StructureFactory#from()
     */
    public static FrameColumnsFactory   from(int intCols, String strNmPref, JalComplexType enmType) throws IllegalArgumentException, NoSuchElementException {
        
        return switch (enmType) {
        case SCALAR -> FrameColumnsFactory.from(intCols, strNmPref, ScalarFactory.from()); 
        case TIMESTAMP -> FrameColumnsFactory.from(intCols, strNmPref, TimestampFactory.from());
        case BYTES -> FrameColumnsFactory.from(intCols, strNmPref, ByteArrayFactory.from());        // throws IllegalArgumentException x 2
        case IMAGE -> FrameColumnsFactory.from(intCols, strNmPref, ImageFactory.from());
        case TENSOR -> FrameColumnsFactory.from(intCols, strNmPref, TensorFactory.from());          // throws IllegalArgumentException x 2
        case STRUCTURE -> FrameColumnsFactory.from(intCols, strNmPref, StructureFactory.from());    // throws IllegalArgumentException x 2
        default -> throw new NoSuchElementException("Unexpected value: " + enmType);
        };
    }
    
    /**
     * <p>
     * Parses and argument string to identify and create a new data columns factory (i.e., <code>FrameColumnsFactory</code> instance).
     * </p>
     * <p>
     * The argument is assumed to be part of an application command line.  For example, the command-line could
     * contain the variable "--cols" which delimits the arguments to this method.  
     * For example, consider the following application command-line 
     * <code>
     * <pre>
     * > java application --cols cnt prefix DTYPE [parameters] [...]
     * </pre>
     * </code>
     * where 
     * <ul>
     * <li>'cnt' is the number of data columns ,</li>
     * <li>'prefix' is the prefix given to each column name,</li> 
     * <li>'DTYPE' is a <code>JalComplexType</code> enumeration constant specifying column type ,</li>
     * <li>'parameters' are the set of configuration parameters for the datum factory <code>parse(String...)</code> operation,</li>
     * <li>... are any additional application command-line parameters.</li>
     * </ul>
     * </p>
     * <p>
     * <h2>Caveat</h2>
     * Clearly it is not necessary for the arguments to be obtained from an application command line as described.  
     * So long as the stated conditions and formats are followed the method will create and return an appropriate 
     * Data Type configuration record.
     * </p> 
     * <p>
     * <h2>Argument Format</h2>
     * With reference to the above example, the format of the argument collection is given by the following:
     * <code>
     * <pre>
     *      cnt prefix DTYPE [datum factory parameters]
     * </pre>
     * </code>
     * where again
     * <ul>
     * <li>'cnt' is the number of data columns, </li>
     * <li>'prefix' is the prefix given to each column name,</li> 
     * <li>'DTYPE' is a <code>JalComplexType</code> enumeration constant specifying column type,</li>
     * <li>'datum factory parameters' are the configuration parameters for the datum factory <code>parse(String...)</code> operation.</li>
     * </ul>
     * Note that the column names for the returned frame column factory are built by appending an index value,
     * from 0 to <code>'cnt' - 1</code>, to the <code>'prefix'</code> string parameter, as in convenience creator 
     * <code>{@link #from(int, String, IDatumFactory)}</code>.
     * </p>
     * <p>
     * <h2>Datum Factories</h2>
     * The datum factory type used by the returned <code>FrameColumnsFactory</code> instanced is given by the 
     * <code>DTYPE</code> value according to the following:
     * <ul>
     * <li><code>{@link JalComplexType#SCALAR}</code> - <code>{@link ScalarFacgtory}</code>.</li>
     * <li><code>{@link JalComplexType#BYTES}</code> - <code>{@link ByteArrayFactory}</code>.</li>
     * <li><code>{@link JalComplexType#TIMESTAMP}</code> - <code>{@link TimestampFactory}</code>.</li>
     * <li><code>{@link JalComplexType#IMAGE}</code> - <code>{@link ImageFactory}</code>.</li>
     * <li><code>{@link JalComplexType#TENSOR}</code> - <code>{@link TensorFactory}</code>.</li>
     * <li><code>{@link JalComplexType#STRUCTURE}</code> - <code>{@link StructureFactory}</code>.</li>
     * </ul>
     * Thus, the number of elements within the arguments <code>'datum factory parameters'</code> is dependent upon the 
     * <code>JalComplexType</code> identified by '<code>DTYPE</code>'.  
     * The argument set contains the parameters necessary to configure the appropriate value generator for
     * column data.
     * If the number of arguments is not appropriate for desired datum factory type an exception is thrown.
     * </p>
     * <p>
     * See the documentation for the parsing method <code>parse(String...)</code> for the associated datum factory
     * for details on the format of its <code>'datum factory parameters'</code> argument (of type <code>String[]</code>).
     * For example, when '<code>DTYPE</code>' == <code>{@link JalComplexType#SCALAR}</code> see
     * <code>{@link ScalarFactory#parse(String...)}</code>.
     * </p>
     *  
     * @param args  argument string defining the configuration for returned frame columns factory
     * 
     * @return  a new <code>FrameColumnsFactory</code> instance as defined by the parsed argument values
     * 
     * @throws TypeNotPresentException  invalid enumeration constant (e.g., the 1st argument was not a <code>JalComplexType</code>)
     * @throws NumberFormatException    invalid numeric expression (typically for 'lngSeed' value)
     * @throws ConfigurationException   the argument contained the wrong number of arguments for the <code>JalComplexType</code>
     * @throws UnsupportedOperationException invalid field value format (typically 'numIncr' was invalid)
     * @throws MalformedParametersException  an enumeration constant within the argument set was not recognized (IMAGE)
     * @throws NoSuchElementException   the column data type was unrecognized (i.e., 'DTYPE' was not supported)
     */
    public static FrameColumnsFactory   parse(String...args) throws TypeNotPresentException, NumberFormatException, ConfigurationException, UnsupportedOperationException, MalformedParametersException {
        if (args.length < 1) 
            return FrameColumnsFactory.from();
        
        // Get the column count 
        int     cntCols = Integer.valueOf(args[0]);
        if (args.length < 2)
            return FrameColumnsFactory.from(cntCols);
        
        // Get the column name prefix
        String  strNmPref = args[1];
        if (args.length < 3)
            return FrameColumnsFactory.from(cntCols, strNmPref); // throws UnsupportedOperationException

        
        // Get the Datum Type of the column values
        JalComplexType  enmType = JalComplexType.valueFrom(args[2]); // throws TypeNotPresentException
        
        // Parse the data factory parameters if provided
        String[]    arrFacCfg = (args.length < 4) ? new String[0] : Arrays.copyOfRange(args, 3, args.length);
        
        IDatumFactory      facValues = switch (enmType) {
        case SCALAR -> ScalarFactory.parse(arrFacCfg);    // throws TypeNotPresentException, NumberFormatException, UnsupportedOperationException
        case BYTES -> ByteArrayFactory.parse(arrFacCfg);   // throws NumberFormatException
        case IMAGE -> ImageFactory.parse(arrFacCfg);       // throws NumberFormatException, TypeNotPresentException
        case TENSOR -> TensorFactory.parse(arrFacCfg);      // throws IllegalArgumentException, ConfigurationException, NumberFormatException, TypeNotPresentException, UnsupportedOperationException 
        case STRUCTURE -> StructureFactory.parse(arrFacCfg);  // throws ConfigurationException, NumberFormatException, TypeNotPresentException, UnsupportedOperationException
        default ->
            throw new NoSuchElementException(JavaRuntime.getQualifiedMethodNameSimple() + " - Data type not supported: " + enmType);
        };
        
        // Create and return the data columns configuration
        return FrameColumnsFactory.from(cntCols, strNmPref, facValues);
    }
 
    /**
     * <p>
     * Retrieves and returns the default ingestion frame data columns specifications for the default 
     * ingestion frame factory configuration.
     * </p>
     * <p>
     * The JAL Tools default configuration contains a default ingestion frame configuration.  This configuration is
     * used by ingestion frame factories to create <code>{@link IngestionFrame}</code> instances when no explicit
     * configuration is given.
     * </p>
     * </p>
     * The returned (ordered) list of <code>IFrameColumnsFactory</code> implementations specifies all the data columns 
     * in the default ingestion frame.  The timestamps for an ingestion frame are specified separately in 
     * <code>{@link FrameTimestampsFactory#defaultFrame()}</code> method. 
     * </p>
     * <p>
     * The method retrieves the default data column specifications contained in the <code>{@link JalToolsColumnsConfig}</code>
     * structure class list within the <code>{@link JalToolsConfig}</code> default configuration.  The parameters
     * for each column are parsed and a new <code>IFrameColumnsFactory</code> implementation is created for each column.
     * The column configurations are returned in the order in which they appear in the JAL Tools default configuration.
     * </p>
     * 
     * @return  a list of new <code>IFrameColumnsFactory</code> implementations as specified in the JAL Tools default configuration
     * 
     * @throws NumberFormatException    a bad numeric format was encountered (typically integer valued parameter)
     * @throws DateTimeParseException   timestamp factory was specified with bad ISO-8601 date/time/duration format
     * @throws TypeNotPresentException  unrecognized enumeration constant (scalar factory JalScalarType or image factory BufferedImage.Format)   
     * @throws ConfigurationException   tensor factory had bad shape 
     * @throws UnsupportedOperationException    scalar factory had bad 'numIncr' parameter
     * @throws NoSuchElementException   the column type is unrecognized (unsupported) 
     * @throws IllegalArgumentException either empty name collection or value factory is <code>null</code>
     */
    public static List<IFrameColumnsFactory<Object>> defaultFrame() throws NumberFormatException, TypeNotPresentException, ConfigurationException, UnsupportedOperationException, NoSuchElementException, IllegalArgumentException {
        List<JalToolsColumnsConfig>         lstColDefCfgs =  CFG_FRM_DEF.columns;
        List<IFrameColumnsFactory<Object>>  lstFacCols = new ArrayList<>(lstColDefCfgs.size());
        
        for (JalToolsColumnsConfig cfg : lstColDefCfgs) {
            IFrameColumnsFactory<Object> facCol = FrameColumnsFactory.from(cfg);    // throws all exceptions
            
            lstFacCols.add(facCol);
        }
        
        return lstFacCols;
    }
    
    
    
    //
    // Class Support Methods
    //
    
    /**
     * <p>
     * Determines the data column factory column type from the datum factory instance type.
     * </p>
     * <p>
     * Switches through the supported datum factory instance types to determine the appropriate 
     * <code>{@link JalComlexType}</code> enumeration constant.  Specifically,
     * the returned value is given by the following:
     * <ul>
     * <li><code>argument == {@link ScalarFactory} &rarr; {@link JalComplexType#SCALAR}</code>.</li>
     * <li><code>argument == {@link TimestampFactory} &rarr; {@link JalComplexType#TIMESTAMP}</code>.</li>
     * <li><code>argument == {@link ByteArrayFactory} &rarr; {@link JalComplexType#BYTES}</code>.</li>
     * <li><code>argument == {@link ImageFactory} &rarr; {@link JalComplexType#IMAGE}</code>.</li>
     * <li><code>argument == {@link TensorFactory} &rarr; {@link JalComplexType#TENSOR}</code>.</li>
     * <li><code>argument == {@link StructureFactory} &rarr; {@link JalComplexType#STRUCTURE}</code>.</li>
     * </ul>
     * If the argument is neither of the above values an exception is thrown.
     * </p>
     * 
     * @param facValues   the datum factory instance used for simulated data production
     * 
     * @return  the <code>JalComplexType</code> constant associated with the given datum factory instance
     * 
     * @throws UnsupportedOperationException    the datum factory was unrecognized or unsupported
     */
    public static JalComplexType  inferColumnType(IDatumFactory facValues) throws UnsupportedOperationException {
        
        // Switch through supported specification cases:
        if (facValues instanceof ScalarFactory)
            return JalComplexType.SCALAR;
        else if (facValues instanceof TimestampFactory)
            return JalComplexType.TIMESTAMP;
        else if (facValues instanceof ByteArrayFactory)
            return JalComplexType.BYTES;
        else if (facValues instanceof ImageFactory)
            return JalComplexType.IMAGE;
        else if (facValues instanceof TensorFactory)
            return JalComplexType.TENSOR;
        else if (facValues instanceof StructureFactory)
            return JalComplexType.STRUCTURE;
        else
            throw new UnsupportedOperationException(JavaRuntime.getQualifiedMethodNameSimple()
                    + " - Unrecognized datum factory instance: " + facValues.getClass().getName());
    }
    
    /**
     * <p>
     * Convenience method for calling the parsing creator of the datum factory associated with the 
     * given complex type.
     * </p>
     * <p>
     * This is a convenience method for instantiating data factory according to their
     * type specification and parsing creator (i.e., <code>parse(String...)</code>).  
     * If the type of a datum factory specification is known a priori it is best to use its creators
     * directly.    
     * This method is used internally for creating the <code>{@link IDatumFactory}</code> implementation according 
     * to type.  Normally it would be left private but since there is no state, only associations, it is
     * left public.
     * </p>
     * <p> 
     * The method first identifies the supported datum factory specification through the 
     * associated <code>{@link JalComplexType}</code> constant.  (See the documentation for 
     * <code>{@link FrameColumnsFactory}</code> for the supported datum factories and their associated
     * <code>{@link JalComplexType}</code> enumeration constants.)  The <code>parse(String...)</code>
     * creator of the datum factory is then called with the given arguments.
     * </p>
     * 
     * @param enmType   data type of the datum factory (i.e., data column type) 
     * @param args      arguments to the parsing creator of the datum factory specification 
     * 
     * @return  a new datum factory implementation determined by the arguments
     * 
     * @throws TypeNotPresentException          unknown <code>JalScalarType</code> enumeration constant (scalar factory)
     * @throws NumberFormatException            invalid numeric format (e.g., scalar factory bad 'numIncr' or 'lngSeed') 
     * @throws UnsupportedOperationException    unable to create 'numIncr' field for numeric value type (scalar factory)
     * @throws MissingResourceException         timestamp factory had empty arguments
     * @throws DateTimeParseException           bad ISO-8601 time and/or duration format (e.g., timestamp factory period, start, etc.) 
     * @throws ConfigurationException           the tensor shape was invalid (e.g., an axis size could not be parsed, non-positive axis size, etc.)
     * @throws NoSuchElementException           unrecognized <code>{@link JalComplexType}</code> constant in argument  
     */
    public static IDatumFactory parseDatumFactory(JalComplexType enmType, String... args) throws TypeNotPresentException, NumberFormatException, UnsupportedOperationException, MissingResourceException, DateTimeParseException, ConfigurationException, NoSuchElementException {
    
        return switch (enmType) {
        case SCALAR -> ScalarFactory.parse(args);       // throws TypeNotPresentException, NumberForamtException, UnsupportedOperationException
        case BYTES -> ByteArrayFactory.parse(args);     // throws NumberFormatException
        case TIMESTAMP -> TimestampFactory.parse(args); // throws MissingResourceException, NumberFormatException, DateTimeParseException
        case IMAGE -> ImageFactory.parse(args);         // throws NumberFormatException, TypeNotPresentException
        case TENSOR -> TensorFactory.parse(args);       // throws ConfigurationException, NumberFormatException, TypeNotPresentException, UnsupportedOperationException
        case STRUCTURE -> StructureFactory.parse(args); // throws NumberForamtException, TypeNotPresentException, UnsupportedOperationException
        default -> throw new NoSuchElementException("Unexpected value: " + enmType);
        };
    }
    
    
    //
    // JAL Library Resources
    //

    /** JAL Tools default configuration parameters for ingestion frame factories */
    private static final JalToolsFramesConfig           CFG_FRM_DEF = JalToolsConfig.getInstance().datagen.frames;
    
    /** JAL Tools default configuration parameters for column factories */
    private static final JalToolsColumnsConfig          CFG_COL_DEF = JalToolsConfig.getInstance().datagen.columns;
    
    
    // 
    // Record Constants - Default Values
    //
    
    /** The default column name prefix */
    public static final String          STR_NM_PREF_DEF = CFG_COL_DEF.name;
    
    /** The default column count */
    public static final int             INT_COL_CNT_DEF = CFG_COL_DEF.count;
    
    /** The default column type */
    public static final JalComplexType  ENM_COL_TYPE_DEF = CFG_COL_DEF.type;
    
    /** The default column value factory specification parameters (parse string) */
    public static final String[]        ARR_FAC_SPEC_DEF = CFG_COL_DEF.factory;

    
    //
    // Defining Attributes - Configuration
    //
    
    /** The names of each column */
    private final Set<String>           setColNms; 
    
//    /** The size of each column - number of data values */
//    private final int                   szCols;
    
    /** The value factory for generating column values */
    private final IDatumFactory     facValues;
    
    
    //
    // Consistent Attributes
    //
    
    /** The number of columns to generate */
    private final int                   cntCols;
    
    /** The Data Platform supported data type of the data column */
    private final DpSupportedType       enmColType;
    
    
    //
    // Constructors
    //
    
    /**
     * <p>
     * Constructs a new <code>FrameColumnsFactory</code> instance.
     * </p>
     *
     * @param setColNms set of unique column names
     * @param szCols    the size of each data column (i.e., number of rows)
     * @param facValues the data value factory producing simulated column values
     * 
     * @throws IllegalArgumentException either empty name collection or value factory is <code>null</code>
     */
    public FrameColumnsFactory(Set<String> setColNms, IDatumFactory facValues) throws IllegalArgumentException {
        
        // Check arguments
        if (setColNms.size() < 1)
            throw new IllegalArgumentException(JavaRuntime.getQualifiedMethodNameSimple() + " - Empty column name set.");
//        if (szCols < 1) 
//            throw new IllegalArgumentException(JavaRuntime.getQualifiedMethodNameSimple() + " - Column size must be > 0.");
        if (facValues == null)
            throw new IllegalArgumentException(JavaRuntime.getQualifiedMethodNameSimple() + " - Must provide a non-null value factory.");
        
        this.setColNms = setColNms;
//        this.szCols = szCols;
        this.facValues = facValues;
        
        this.cntCols = this.setColNms.size();
        this.enmColType = this.facValues.getDatumType();
    }

    
    //
    // IFrameColumnsFactory Interface
    //
    
    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IFrameColumnsFactory#getColumnCount()
     */
    @Override
    public final int getColumnCount() {
        return this.cntCols;
    }
    
    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IFrameColumnsFactory#getColumnNames()
     */
    @Override
    public final Set<String> getColumnNames() {
        return this.setColNms;
    }
    
//    /**
//     * @see com.ospreydcs.dp.jal.tools.common.datagen.IFrameColumnsFactory#getColumnSize()
//     */
//    @Override
//    public final int getColumnSize() {
//        return this.szCols;
//    }
    
    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IFrameColumnsFactory#getColumnType()
     */
    @Override
    public final DpSupportedType getColumnType() {
        return this.enmColType;
    }
    
    /**
     * <p>
     * Creates a new collection of data columns according to the configuration record supplied at
     * construction.
     * </p>
     * <p>
     * Returned object is an immutable array list (i.e., a "vector") created from Java streams.
     * The columns are ordered according to the ordering of the column name <code>Set</code>
     * provided at creation/construction.  The values within each column are generated by the
     * data factory <code>{@link IDatumFactory}</code> provided at creation/construction.
     * </p>
     * 
     * @param   szCols  the size of all data columns returned (i.e., the number of rows)
     * 
     * @return  vector of data columns containing simulated data
     * 
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IFrameColumnsFactory#build()
     */
    @Override
    public ArrayList<IDataColumn<Object>> build(int szCols) {

        // Create (immutable) list of columns
        ArrayList<IDataColumn<Object>>   lstCols = this.setColNms
                .stream()
                .<IDataColumn<Object>>map(name -> this.buildColumn(name, szCols))
                .collect(
                        ArrayList::new, 
                        (vec, col) -> vec.add(col), 
                        (vec1, vec2) -> vec1.addAll(vec2)
                        );
        
        return lstCols;
    }
    
    
    //
    // Comparable<IFrameColumnsFactory<Object>> Interface
    //
    
    /**
     * <p>
     * Provides the ordering of <code>IFrameColumnsFactory</code> implementations within Java collections.
     * </p>
     * <p>
     * This method provides an order based upon the number of columns <code>{@link #getColumnCount()}</code>.
     * The method first checks for equivalence (i.e., <code>{@link #equals(Object)}</code> returning 0
     * if so.
     * Then, if the number of columns is less than or equal to the that of the argument a -1 value is returned,
     * otherwise a +1 is returned.
     * </p
     * <p>
     * <h2>Formula</h2>
     * The explicit formula for the the returned value for 2 <code>IFrameColumnsFactory</code> instances is given below.
     * Let <code>A</code> and <code>B</code> be the implementations under comparison where <code>A = this</code> 
     * and <code>B</code> is the argument.
     * Then  
     * <ul>
     * <li> 0 &lArr; <code>A.equals(B) == true</code>.</li>
     * <li>-1 &lArr; <code>A.getColumnsCount() <= B.getColumnsCount()</code>.</li>
     * <li>+1 &lArr; <code>A.getColumnsCount() > B.getColumnsCount()</code>.</li>
     * </ul>
     * Note that the above formula prevents clobbering of non-equivalent <code>IFrameColumnsFactory</code> implementations
     * with equal column counts.
     * </p>
     * <p>
     * <h2>Reflexativity</h2>
     * Thus it is not a reflective operation as the operation does not commute.  
     * Specifically,  
     * <pre>
     * <code>
     *  A.compareTo(B) &ne; B.compareTo(A) iff A.getColumnsCount() == B.getColumnsCount()
     * </code>
     * </pre> 
     * Thus, the operation is not strictly as defined in <code>{@link Comparable#compareTo(Object)}</code>.
     * However, the operation is transitive.  Specifically, for implementations <code>A, B, C</code>
     * <pre>
     * <code>
     *   A.compareTo(B) > 0 && B.compareTo(C) > 0 &rArr; A.compareTo(C) > 0
     * </code>
     * <pre> 
     * 
     * @param facCols  the <code>IFrameColumnsFactory</code> implementation to compare with this instance
     *  
     * @return  0 if this{@link #equals(Object)}, -1 if this.{@link #getColumnCount()} <= facCols.{@link #getColumnCount()}, else +1
     * 
     * @see java.lang.Comparable#compareTo(java.lang.Object)
     */
    @Override
    public int compareTo(IFrameColumnsFactory<Object> facCols) {
        
        // Check first for equivalence
        if (this.equals(facCols))
            return 0;
        
        // Then order by column count
        if (this.cntCols <= facCols.getColumnCount())
            return -1;
        else
            return +1;
    }

    
    //
    // Object Overrides
    //
    
    /**
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        
        if (obj instanceof FrameColumnsFactory fac) {
            boolean bolResult = this.setColNms.equals(fac.setColNms)
                              && this.facValues.equals(fac.facValues)
                              && this.cntCols == fac.cntCols
                              && this.enmColType == fac.enmColType;
            
            return bolResult;
        }
        
        return false;
    }

    /**
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        final int           cntHead = 10;
        final List<String>  lstHead = this.setColNms.stream().toList().subList(0, cntHead);
        StringBuilder       buf = new StringBuilder();
        
        buf.append("Column count            : " + this.cntCols + "\n");
        buf.append("Column type             : " + this.enmColType + "\n");
        buf.append("Column names (first " + cntHead + "): " + lstHead + "\n");
        buf.append("Datum Factory \n");
        buf.append(this.facValues);
        
        return buf.toString();
    }

    
    //
    // Support Methods
    //
    
    /**
     * <p>
     * Creates a new data column with the given name and appropriate size.
     * </p>
     * <p>
     * The attribute <code>{@link #facValues}</code> is used to create the new values for
     * the data column.  The type parameter for the new column is given by <code>{@link #enmDataType}</code>
     * and the size of the column (i.e., number of rows) is given by <code>{@link #szCols}</code>.
     * </p>
     * <p>
     * Currently the concrete type of the returned interface is given by <code>{@link StaticDataColumn}</code>.
     * This class is provided in the Java API client library.
     * </p>
     * 
     * @param strName   data column name
     * @param szCols    the size of the data column returned (i.e., the number of rows)
     * 
     * @return  new, populated implementation of the <code>IDataColumn</code> interface.
     */
    private IDataColumn<Object> buildColumn(String strName, int szCols) {
        
        // Create the value vector container and pack it with new values
        ArrayList<Object>   vecVals = new ArrayList<>(szCols);
        for (int i=0; i<szCols; i++) {
            Object objVal = this.facValues.nextDatum();
            
            vecVals.add(objVal);
        }
        
        // Create the new column
        StaticDataColumn<Object>    col = StaticDataColumn.from(strName, this.enmColType, vecVals);
        
        return col;
    }
    
    /**
     * <p>
     * Creates a new <code>IFrameColumnsFactory</code> implementation from the given data column default parameters structure class.
     * </p>
     * <p>
     * The given structure class is assumed to originate from the JAL Tools default configuration
     * <code>{@link JalToolsConfig}</code>.  This method extracts the attributes of the structure class and uses
     * them to configure the returned data column factory.
     * </p>
     * 
     * @param cfgCols   data column default parameters structure class
     * 
     * @return  new <code>IFrameColumnsFactory</code> implementation configured from the argument attributes
     * 
     * @throws TypeNotPresentException      an enumeration constant was not recognized
     * @throws NumberFormatException        invalid number format (e.g., seed value for scalar factory specification)
     * @throws UnsupportedOperationException unable to create 'numIncr' field in scalar factory specification
     * @throws MissingResourceException     timestamp factory had empty arguments
     * @throws DateTimeParseException       invalid format for ISO-8601 time and/or duration specification 
     * @throws ConfigurationException       tensor shape was invalid
     * @throws NoSuchElementException       the 'enmType' constant was not supported
     * @throws IllegalArgumentException     either empty name collection or value factory is <code>null</code>
     */
    private static IFrameColumnsFactory<Object> from(JalToolsColumnsConfig cfgCols) throws TypeNotPresentException, NumberFormatException, UnsupportedOperationException, MissingResourceException, DateTimeParseException, ConfigurationException, NoSuchElementException, IllegalArgumentException {
        
        // Create column names
        int             intCols = cfgCols.count;
        String          strNmPref = cfgCols.name;
        
        Set<String>     setColNms = IntStream.range(0, intCols).<String>mapToObj(i -> strNmPref + Integer.toString(i)).collect(TreeSet::new, TreeSet::add, TreeSet::addAll);
        
        // Create datum factory
        JalComplexType  enmType = cfgCols.type;
        String[]        arrFacArgs = cfgCols.factory;
        
        IDatumFactory   facCols = FrameColumnsFactory.parseDatumFactory(enmType, arrFacArgs);    // throws all exceptions
        
        return FrameColumnsFactory.from(setColNms, facCols);    // throws IllegalArgumentException
    }
    
}
