#
# Project: dp-jal
# File:    jal-tools-config.yml
# Type:    YAML
#
# Configuration parameters for the Java API Library tools.
#
# The tool set included with the Java API Library interface to the Data Platform requires some configuration
# parameters for proper operations.  All configuration parameters for all tools are included here.
#
# Some configuration parameters are available for performance tuning, especially for tools that measure
# Java API Library performance or Data Platform Core Services performance. 
#
# Author: Christopher K. Allen
# Since: May 4, 2025
#
#
# NOTES:
#
# - This parameter set can be modified according to the Data Platform cnofiguration and installations requirements.
# - These parameters are available programmatically within the Java structure class 'DpApiToolsConfig'.
# - The name indexing for the PV within the Data Platform test archive is 1-based, opposed to Java standard 0-basing.
# - The data source (PV) names are formed by appending the PV index (1-based) to the pvPrefix value.
# - The indexes within the query/testArchive YAML block are 0-based Java indexes (they are incremented by 1 to form the PV names)
# - Data sources pvPrefix+pvIndexStartClock through pvPrefix+(pvIndexStartClock+pvCountClock) utilize a uniform sampling clock
# - Data sources pvPrefix+pvIndexStartTmsList through pvPrefix+(pvIndexStartTmsList+pvCountTmsList) utilize explicit timestamp lists
# - Explicit timestamp lists are only available after Data Platform release 1.8 and its accompanying app-run-test-data-generator
#  
         
testArchive:   # Data Platform test archive properties (generated with utility 'app-run-test-data-generator')
   range:
     start: 2023-10-31T15:51:02.000+00:00 # first timestamp w/in archive : JAL_TOOLS_TEST_ARCHIVE_RANGE_START
     end: 2023-10-31T15:52:01.999+00:00  # last timestamp w/in archive   : JAL_TOOLS_TEST_ARCHIVE_RANGE_END 
   pvs:
      prefix: "dpTest_"         # PV name prefix - suffix is index         : JAL_TOOLS_TEST_ARCHIVE_PVS_PREFIX
      types:                    # types list - DpSupportedType enumeration : JAL_TOOLS_TEST_ARCHIVE_PVS_TYPES
        - DOUBLE
      clock:
         period: 1              # Sampling clock periods for all PVs               : JAL_TOOLS_TEST_ARCHIVE_PVS_CLOCK_PERIOD
         units: MILLISECONDS    # Sampling clock time units - TimeUnit Enumeration : JAL_TOOLS_TEST_ARCHIVE_PVS_CLOCK_UNITS
      count:
         total: 4000            # Total number of PVs in archive        : JAL_TOOLS_TEST_ARCHIVE_PVS_COUNT_TOTAL
         clocked: 3800          # Number of (uniform) clocked PVs       : JAL_TOOLS_TEST_ARCHIVE_PVS_COUNT_CLOCKED
         tmsList: 200           # Number of explicit timestamp list PVs : JAL_TOOLS_TEST_ARCHIVE_PVS_COUNT_TMS_LIST
      indexes:
         clocked: 0             # 1st clocked PV index (0-based index   : JAL_TOOLS_TEST_ARCHIVE_PVS_INDEXES_CLOCKED
         tmsList: 3800          # 1st timestamp list PV index (0-based) : JAL_TOOLS_TEST_ARCHIVE_PVS_INDEXES_TMS_LIST
       
datagen:       # JAL Tools simulated data generation default configuration parameters
   frames:                  # Ingestion frame generation parameter
      tags:                    # common tag values given to frames   : JAL_TOOLS_DATAGEN_FRAMES_TAGS
         - "Simulated"
         - "JAL Tools"
         - "Default"
      attributes:              # common attribute pairs given to frames: JAL_TOOLS_DATAGEN_FRAMES_ATTRIBUTES
         Location: "Testbed"
         Source: "Simulator"
         Configuration: "jal-tools-config.yml"
      timestamps:              # Default timestamps for ingestion frames        
         type: SAMPLING_CLOCK  # 'DpTimestampCase' enumeration         : JAL_TOOLS_DATAGEN_FRAMES_TIMESTAMPS_TYPE
         start: 2023-10-31T15:51:02.000+00:00 # first timestamp (ISO)  : JAL_TOOLS_DATAGEN_FRAMES_TIMESTAMPS_START
         period: PT0.001S      # sampling period (ISO-8605 format)     : JAL_TOOLS_DATAGEN_FRAMES_TIMESTAMPS_PERIOD
         delay: P0.0S          # sampling delay from start instant     : JAL_TOOLS_DATAGEN_FRAMES_TIMESTAMPS_DELAY
         count: 1000           # samples per frame (row count)         : JAL_TOOLS_DATAGEN_FRAMES_TIMESTAMP_COUNT
      columns:                 # Default columns for ingestion frames
         - name: JalDbl_       # column bank name (also prefix for cols)
           count: 100          # number of columns in column bank
           type: SCALAR        # 'JalHeteroType' enumeration - datum type of all columns in column bank
           factory: "DOUBLE"   # parameters for datum factory (depends upon 'type')
         - name: JalStruct_
           count: 1
           type: STRUCTURE
           factory: "2 3 INTEGER false"
   values:                  # Data value generation parameters
      scalar:               # Scalar factory default configuration parameters
         type: DOUBLE          # JalScalarType enumeration constant    : JAL_TOOLS_DATAGEN_VALUES_SCALAR_TYPE
         stringPrefix: "str:"  # prefix for string values (type=STRING): JAL_TOOLS_DATAGEN_VALUES_SCALAR_STRING_PREFIX
         random:            # Random number generation parameters      : JAL_TOOLS_DATAGEN_VALUES_SCALAR_RANDOM_ENABLE_{PROP}
            enabled: false     # enable/disable random number generator (WARNING: random generation can be expensive)
            seed: 0            # random  generator seed (0 for random seed) : JAL_TOOLS_DATA_GEN_VALUES_SCALAR_RANDOM_SEED
         increment:         # Value increment parameters for non-random generation : JAL_TOOLS_DATAGEN_SCALAR_INCREMENT_{FIELDNAME}
            seed: 0            # seed (start) value (type long)
            booleanv: 1        # increment value for boolean value generation 
            integerv: 1        # increment value for integer value generation
            longv: 5           # increment value for long value generation
            floatv: 0.1        # increment value for float value generation
            doublev: 0.01      # increment value for double value generation
            stringv: 1         # increment value for string value generator (full string includes numeric suffix)
      timestamp:            # Timestamp factory default configuration parameters
         random:               # Random timestamp generation parameters
            enabled: false     # enable/disable random timestamp values      : JAL_TOOLS_DATA_GEN_VALUES_TIMESTAMP_RANDOM_ENDABLED
            seed: 0            # random  generator seed (0 for random seed)  : JAL_TOOLS_DATA_GEN_VALUES_TIMESTAMP_RANDOM_SEED
         increment:
            start: 1970-01-01T00:00:00Z # first timestamp (ISO format) : JAL_TOOLS_DATAGEN_TIMESTAMP_INCREMENT_START
            period: PT0.001S   # duration between timestamps (ISO PnDTnHnMn.nS format) : JAL_TOOLS_DATAGEN_TIMESTAMP_INCREMENT_PERIOD
      bytes:                # Byte array factory default configuration parameters
         size: 65536           # byte array size (in bytes)                  : JAL_TOOLS_DATAGEN_VALUES_BYTES_SIZE
      image:                # Image factory default configuration parameters
         separator: ":"        # separator between prefix and image count    : JAL_TOOLS_DATAGEN_VALUES_IMAGE_SEPARATOR
         namePrefix: "img"     # image name prefix (suffixed by image count) : JAL_TOOLS_DATAGEN_VALUES_IMAGE_NAME_PREFIX
         format: RAW           # 'BufferedImage.Format' enumeration          : JAL_TOOLS_DATAGEN_VALUES_IMAGE_FORMAT
         size: 65536           # image size (in bytes)                       : JAL_TOOLS_DATAGEN_VALUES_IMAGE_SIZE
      tensor:              # Tensor (multi-dimensional array) factory default configuration parameters
         shape:                # tensor default shape- axes sizes 1st to last: JAL_TOOLS_DATAGEN_VALUES_TENSOR_SHAPE
         - 2                   # 1st axis size
         - 3                   # 2nd axis size
         - 4                   # 3rd axis size (..., etc.)
         elements:             # Tensor element properties - scalar factory configuration (default parameters taken from 'scalar' configuration)
            type: DOUBLE       # 'JalScalarType' constant - element data type : JAL_TOOLS_DATAGEN_VALUES_TENSOR_ELEMENTS_TYPE 
            random:            # random number generation of tensor elements
               enabled: false  # enable/disable random number generation      : JAL_TOOLS_DATAGEN_VALUES_TENSOR_ELEMENTS_RANDOM_ENABLED
               seed: 0         # random number generator seed (0 for 'random'): JAL_TOOLS_DATAGEN_VALUES_TENSOR_ELEMENTS_RANDOM_SEED
      structure:            # Structure factory default configuration parameters
         tree:                 # Tree structure default configuration  
            depth: 3           # depth of tree (nodes until terminal nodes)  : JAL_TOOLS_DATAGEN_VALUES_STRUCTURE_TREE_DEPTH
            fanout: 2          # sub-node fan-out of each tree node          : JAL_TOOLS_DATAGEN_VALUES_STRUCTURE_TREE_FANOUT
         fieldValues:          # Properties for structure field value generation
            type: INTEGER      # 'JalScalarType' enumeration - field type     : JAL_TOOLS_DATAGEN_VALUES_STRUCTURE_FIELD_VALUES_TYPE
            random:            # random number generation of structure field values
               enabled: false  # enable/disable random number generation      : JAL_TOOLS_DATAGEN_VALUES_STRUCTURE_FIELD_VALUES_RANDOM_ENABLED
               seed: 0         # random number generator seed (0 for 'random'): JAL_TOOLS_DATAGEN_VALUES_STRUCTURE_FIELD_VALUES_RANDOM_SEED
         fieldNames:           # Properties for structure field name generation
            prefix: "F"        # prefix given to structure field names  : JAL_TOOLS_DATAGEN_VALUES_STRUCTURE_FIELD_NAMES_PREFIX
            separator: ":"     # separator placed between field indices : JAL_TOOLS_DATAGEN_VALUES_STRUCTURE_FIELD_NAMES_SEPARATOR
            unique:            # Properties for unique field name generation
              enabled: false   # enable/disable unique field name generation : JAL_TOOLS_DATAGEN_VALUES_STRUCTURE_FIELD_NAMES_UNIQUE_ENABLED 
              prefix: "S"      # name token prefix prepended to field name   : JAL_TOOLS_DATAGEN_VALUES_STRUCTURE_FIELD_NAMES_UNIQUE_PREFIX
              separator1: "#"  # separator placed between structure indices  : JAL_TOOLS_DATAGEN_VALUES_STRUCTURE_FIELD_NAMES_UNIQUE_SEPARATOR1
              separator2: "-"  # separator between struct token and field nm : JAL_TOOLS_DATAGEN_VALUES_STRUCTURE_FIELD_NAMES_UNIQUE_SEPARATOR2
       
output:         # JAL Tools (General) default output location - this should be related to DP_JAL_OUTPUT environment variable
   path: test/output         # path location relative to execution     : JAL_TOOLS_OUTPUT_PATH
         

    
   