#
# Project: dp-jal
# File:    jal-tools-config.yml
# Type:    YAML
#
# Configuration parameters for the Java API Library tools.
#
# The tool set included with the Java API Library interface to the Data Platform requires some configuration
# parameters for proper operations.  All configuration parameters for all tools are included here.
#
# Some configuration parameters are available for performance tuning, especially for tools that measure
# Java API Library performance or Data Platform Core Services performance. 
#
# Author: Christopher K. Allen
# Since: May 4, 2025
#
#
# NOTES:
#
# - This parameter set can be modified according to the Data Platform cnofiguration and installations requirements.
# - These parameters are available programmatically within the Java structure class 'DpApiToolsConfig'.
# - The name indexing for the PV within the Data Platform test archive is 1-based, opposed to Java standard 0-basing.
# - The data source (PV) names are formed by appending the PV index (1-based) to the pvPrefix value.
# - The indexes within the query/testArchive YAML block are 0-based Java indexes (they are incremented by 1 to form the PV names)
# - Data sources pvPrefix+pvIndexStartClock through pvPrefix+(pvIndexStartClock+pvCountClock) utilize a uniform sampling clock
# - Data sources pvPrefix+pvIndexStartTmsList through pvPrefix+(pvIndexStartTmsList+pvCountTmsList) utilize explicit timestamp lists
# - Explicit timestamp lists are only available after Data Platform release 1.8 and its accompanying app-run-test-data-generator
#  
         
testArchive:   # Data Platform test archive properties (generated with utility 'app-run-test-data-generator')
   range:
     start: 2023-10-31T15:51:02.000+00:00 # first timestap w/in archive : JAL_TOOLS_TEST_ARCHIVE_RANGE_START
     end: 2023-10-31T15:52:01.999+00:00  # last timestamp w/in archive  : JAL_TOOLS_TEST_ARCHIVE_RANGE_END 
   pvs:
      prefix: "dpTest_"         # PV name prefix - suffix is index         : JAL_TOOLS_TEST_ARCHIVE_PVS_PREFIX
      types:                    # types list - DpSupportedType enumeration : JAL_TOOLS_TEST_ARCHIVE_PVS_TYPES
        - DOUBLE
      clock:
         period: 1              # Sampling clock periods for all PVs               : JAL_TOOLS_TEST_ARCHIVE_PVS_CLOCK_PERIOD
         units: MILLISECONDS    # Sampling clock time units - TimeUnit Enumeration : JAL_TOOLS_TEST_ARCHIVE_PVS_CLOCK_UNITS
      count:
         total: 4000            # Total number of PVs in archive        : JAL_TOOLS_TEST_ARCHIVE_PVS_COUNT_TOTAL
         clocked: 3800          # Number of (uniform) clocked PVs       : JAL_TOOLS_TEST_ARCHIVE_PVS_COUNT_CLOCKED
         tmsList: 200           # Number of explicit timestamp list PVs : JAL_TOOLS_TEST_ARCHIVE_PVS_COUNT_TMS_LIST
      indexes:
         clocked: 0             # 1st clocked PV index (0-based index   : JAL_TOOLS_TEST_ARCHIVE_PVS_INDEXES_CLOCKED
         tmsList: 3800          # 1st timestamp list PV index (0-based) : JAL_TOOLS_TEST_ARCHIVE_PVS_INDEXES_TMS_LIST
       
output:         # JAL Tools (General) default output location - this should be related to DP_JAL_OUTPUT environment variable
   path: test/output         # path location relative to execution     : JAL_TOOLS_OUTPUT_PATH
         

    
   