/*
 * Project: dp-jal
 * File:	DataColumnFactory.java
 * Package: com.ospreydcs.dp.jal.tools.common.datagen.frames
 * Type: 	DataColumnFactory
 *
 * Copyright 2010-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * @author Christopher K. Allen
 * @org    OspreyDCS
 * @since Nov 20, 2025
 *
 */
package com.ospreydcs.dp.jal.tools.common.datagen.frames;

import java.util.ArrayList;

import com.ospreydcs.dp.jal.common.DpSupportedType;
import com.ospreydcs.dp.jal.common.IDataColumn;
import com.ospreydcs.dp.jal.model.table.StaticDataColumn;
import com.ospreydcs.dp.jal.tools.common.datagen.IDataColumnFactory;
import com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory;
import com.ospreydcs.dp.jal.util.JavaRuntime;

/**
 * <p>
 * Factory class for generating single column of <code>IDataColumn</code> instances containing simulated data.
 * </p>
 * <p>
 * Instances of this class are used primarily for column generation within ingestion frame factory class
 * instances.  This column factory creates single columns upon invocation of the <code>{@link #nextColumn()}</code>
 * method.  All data columns contain simulated data of the same data type, specifically, the data type
 * generated by the <code>{@link IDatumFactory}</code> instance provided at creation/construction. 
 * </p>
 * <p>
 * The <code>{@link #nextColumn()}</code> method is used to 
 * <code>IDataColumn</code> objects according to the <code>DataColumnFactory</code> configuration determined
 * at creation/construction.  The the size of each column returned (i.e., the number of rows) is given by the 
 * size argument, while the type of each column data value is
 * given by <code>{@link IDatumFactory#getDatumType()}</code> of the data factory provided at creation/construction.  
 * Column values are generated using the <code>{@link IDatumFactory}</code> by sequential invocation of
 * <code>{@link IDatumFactory#nextDatum()}</code>.
 * </p>
 * <h2>Column Types</h2>
 * The data columns returned by the <code>{@link #nextColumn()}</code> method are implementations of the interface
 * <code>{@link IDataColumn}</code>.  Currently, the underlying implementation is of type
 * <code>{@link StaticDataColumn}</code>.
 * </p>
 *
 * @author Christopher K. Allen
 * @since Nov 20, 2025
 *
 */
public class DataColumnFactory implements IDataColumnFactory<Object> {

    
    //
    // Creators
    //
    
    /**
     * <p>
     * Creates and returns a new <code>DataColumnsFactory</code> instance configured according to the given arguments.
     * </p>
     * <p>
     * The <code>{@link #nextColumn()}</code> method is available for data column creation.  It returns a vector
     * (i.e., <code>{@link ArrayList}</code> of data columns, one for each column name given, containing simulated
     * data produced by the given data value factory.  The size of each column (i.e., the number of rows) is given 
     * by the size argument.
     * See the class documentation on <code>{@link DataColumnsFactory}</code> for more information.
     * </p>
     * 
     * @param strColName    the column name for all generated columns
     * @param szCol         the size of each generated data column (i.e., number of rows)
     * @param facValues     the data value factory producing simulated column values
     * 
     * @return  a new <code>DataColumnsFactory</code> instance ready for data column generation
     *
     * @throws IllegalArgumentException data value factory is <code>null</code>
     * 
     * @see DataColumnsFactory
     */
    public static final DataColumnFactory   from(String strColName, IDatumFactory facValues) throws IllegalArgumentException {
        return new DataColumnFactory(strColName, facValues);
    }
    
    
    //
    // Defining Attributes - Configuration
    //
    
    /** The names of each column */
    private final String                strColNm; 
    
//    /** The size of each column - number of data values */
//    private final int                   szCol;
    
    /** The value factory for generating column values */
    private final IDatumFactory         facValues;
    
    
    //
    // Consistent Attributes
    //
    
    /** The Data Platform supported data type of the data column */
    private final DpSupportedType       enmColType;
    
    
    //
    // Constructors
    //
    
    /**
     * <p>
     * Constructs a new <code>DataColumnFactory</code> instance.
     * </p>
     *
     * @param strColName    the column name for all generated columns
     * @param szCol         the size of each generated data column (i.e., number of rows)
     * @param facValues     the data value factory producing simulated column values
     * 
     * @throws IllegalArgumentException data value factory is <code>null</code>
     */
    public DataColumnFactory(String strColName, IDatumFactory facValues) throws IllegalArgumentException {
        
        // Check arguments
//        if (szCol < 1 )
//            throw new IllegalArgumentException(JavaRuntime.getQualifiedMethodNameSimple() + " - Column size must be > 0");
        if (facValues == null)
            throw new IllegalArgumentException(JavaRuntime.getQualifiedMethodNameSimple() + " - Data value factory cannot be null.");
        
        this.strColNm = strColName;
//        this.szCol = szCol;
        this.facValues = facValues;
        
        this.enmColType = this.facValues.getDatumType();
    }

    
    //
    // IDataColumnFactory Interface
    //
    
    /**
     * <p>
     * Returns the column name for all factory generated columns.
     * </p>
     * 
     * @return  column name for factory generated columns
     * 
     * @see IDataColumnFactory#getColumnName()
     */
    @Override
    public final String getColumnName() {
        return this.strColNm;
    }
    
//    /**
//     * <p>
//     * Returns the size of each column generated, that is, the number of values in the column.
//     * </p>
//     * 
//     * @return  number column values (or "rows")
//     * 
//     * @see IDataColumnFactory#getColumnSize()
//     */
//    @Override
//    public final int getColumnSize() {
//        return this.szCol;
//    }
    
    /**
     * <p>
     * The Data Platform type enumeration for the column values.
     * </p>
     *   
     * @return  the <code>DpSupported</code> type enumeration for column data values
     * 
     * @see IDataColumnFactory#getColumnType()
     */
    @Override
    public final DpSupportedType getColumnType() {
        return this.enmColType;
    }
    
    /**
     * <p>
     * Creates a new data columns according to the configuration supplied at creation/construction.
     * </p>
     * <p>
     * The attribute <code>{@link IDatumFactory}</code> instance provided at creation/construction
     * is used to create the new values for
     * the data column.  The type parameter for the new column is given by <code>{@link #getColumnType()}</code>
     * and the size of the column (i.e., number of rows) is given by <code>{@link #getColumnSize()}</code>.
     * </p>
     * <p>
     * Currently the concrete type of the returned interface is given by <code>{@link StaticDataColumn}</code>.
     * This class is provided in the Java API client library.
     * </p>
     * 
     * @param   szCol   the size of the returned data column (i.e., the number of rows)
     * 
     * @return  new implementation of the <code>IDataColumn</code> interface populated with simulated data
     * 
     * @see IDataColumnFactory#nextColumnn()
     */
    @Override
    public IDataColumn<Object> nextColumn(int szCol) {

        
        // Create the value vector container and pack it with new values
        ArrayList<Object>   vecVals = new ArrayList<>(szCol);
        for (int i=0; i<szCol; i++) {
            Object objVal = this.facValues.nextDatum();
            
            vecVals.add(objVal);
        }
        
        // Create the new column
        StaticDataColumn<Object>    col = StaticDataColumn.from(this.strColNm, this.enmColType, vecVals);
        
        return col;
    }

}
