/*
 * Project: dp-jal
 * File:	ByteArrayFactory.java
 * Package: com.ospreydcs.dp.jal.tools.common.datagen.values
 * Type: 	ByteArrayFactory
 *
 * Copyright 2010-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * @author Christopher K. Allen
 * @org    OspreyDCS
 * @since Nov 23, 2025
 *
 */
package com.ospreydcs.dp.jal.tools.common.datagen.values;

import com.ospreydcs.dp.jal.common.DpSupportedType;
import com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory;
import com.ospreydcs.dp.jal.tools.common.datagen.JalComplexType;
import com.ospreydcs.dp.jal.tools.common.datagen.JalScalarType;
import com.ospreydcs.dp.jal.tools.config.JalToolsConfig;
import com.ospreydcs.dp.jal.tools.config.datagen.values.JalToolsBytesFactoryConfig;
import com.ospreydcs.dp.jal.util.JavaRuntime;

/**
 * <p>
 * A generator of simulated byte-array data values compatible with the Data Platform byte array data values.
 * </p>
 * <p>
 * Class instance are very basic implementations of the <code>{@link IDatumFactory}</code> interface.
 * The <code>{@link #nextDatum()}</code> method simply allocates byte arrays of Java type <code>{@link byte[]}</code> 
 * which is then directly returned.  The values within the byte array are simply the random values within
 * the heap at the time of memory allocation.
 * </p> 
 * <p>
 * <h2>Configuration</h2>
 * The only configuration option is the size of the byte array which is determined at creation/construction.
 * All byte arrays have <code>byte[].length</code> given by that value.
 * </p>
 *
 * @author Christopher K. Allen
 * @since Nov 23, 2025
 *
 */
public class ByteArrayFactory implements IDatumFactory {

    
    //
    // Creators
    //
    
    /**
     * <p>
     * Creates and returns a new instance of <code>ByteArrayFactory</code> with default argument.
     * </p>
     * <p>
     * This creator uses the default value <code>{@link #INT_SIZE_DEF}</code> for the size of the
     * generated byte arrays.
     * </p>
     * <p>
     * The returned <code>ByteArrayFactory</code> produces simulated data values of type <code>byte[]</code>
     * with sizes given by the argument.  All data within the byte arrays are random, simply the heap
     * memory of the array allocated at the time of <code>{@link #nextDatum()}</code> invocation.
     * </p> 
     * 
     * @param szArrays  the size of the generated byte arrays (i.e., number of bytes)
     * 
     * @return  a new <code>ByteArrayFactory</code> ready for simulated data generation
     * 
     * @throws IllegalArgumentException non-positive array size
     */
    public static ByteArrayFactory  from() throws IllegalArgumentException {
        return ByteArrayFactory.from(INT_SIZE_DEF);
    }
    
    /**
     * <p>
     * Creates and returns a new instance of <code>ByteArrayFactory</code> configured according to the argument.
     * </p>
     * <p>
     * This creator is equivalent to the canonical constructor
     * <code>{@link #ByteArrayFactory(int)}</code>.
     * </p>
     * <p>
     * The returned <code>ByteArrayFactory</code> produces simulated data values of type <code>byte[]</code>
     * with sizes given by the argument.  All data within the byte arrays are random, simply the heap
     * memory of the array allocated at the time of <code>{@link #nextDatum()}</code> invocation.
     * </p> 
     * 
     * @param szArrays  the size of the generated byte arrays (i.e., number of bytes)
     * 
     * @return  a new <code>ByteArrayFactory</code> ready for simulated data generation
     * 
     * @throws IllegalArgumentException non-positive array size
     */
    public static ByteArrayFactory  from(int szArrays) throws IllegalArgumentException {
        return new ByteArrayFactory(szArrays);
    }
    
    
    //
    // Library Resources
    //
    
    /** The factory default configuration parameters */ 
    private static final JalToolsBytesFactoryConfig CFG_DEF = JalToolsConfig.getInstance().datagen.values.bytes;
    
    
    /** The default byte array size (in bytes) */
    public static final int     INT_SIZE_DEF = CFG_DEF.size;
    
    
    //
    // Class Constants
    //
    
    /** The datum type of all data produced by this data factory */
    public static final DpSupportedType     ENM_DATUM_TYPE = DpSupportedType.BYTE_ARRAY;
    
    /** The scalar type of all data produced by this data factory */
    public static final JalScalarType       ENM_SCALAR_TYPE = JalScalarType.UNSUPPORTED;
    
    /** The complex type of all data produced by this data factory */
    public static final JalComplexType       ENM_CMPLX_TYPE = JalComplexType.BYTES;
    
    
    //
    // Defining Attributes - Configuration
    //
    
    /** The size of all byte arrays returned by this factory */
    private final int       szArrays; 
    
    
    //
    // Constructor
    //
    
    /**
     * <p>
     * Constructs a new <code>ByteArrayFactory</code> instance.
     * </p>
     *
     * @param szArrays  the size of the generated byte arrays (i.e., number of bytes)
     * 
     * @throws IllegalArgumentException non-positive array size
     */
    public ByteArrayFactory(int szArrays) throws IllegalArgumentException {
        
        // Check argument
        if (szArrays < 0)
            throw new IllegalArgumentException(JavaRuntime.getQualifiedMethodNameSimple()+ " - Array size must be nonzero.");
        
        this.szArrays = szArrays;
    }
    
    
    //
    // Configuration Query
    //
    
    /**
     * <p>
     * Returns the size (in bytes) of all byte arrays generated by this byte array factory.
     * </p>
     * 
     * @return  the array-size configuration parameter provided at creation/construction (in bytes)
     */
    public int  getArraySize() {
        return this.szArrays;
    }
    
    
    //
    // IDatumFactory Interface
    //

    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory#getDatumType()
     */
    @Override
    public DpSupportedType getDatumType() {
        return ENM_DATUM_TYPE;
    }

    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory#getScalarType()
     */
    @Override
    public JalScalarType getScalarType() {
        return ENM_SCALAR_TYPE;
    }


    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory#getComplexType()
     */
    @Override
    public JalComplexType getComplexType() {
        return ENM_CMPLX_TYPE;
    }
    
    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory#nextDatum()
     */
    @Override
    public Object nextDatum() {
        byte[]      arrValue = new byte[this.szArrays];
        
        return arrValue;
    }

}
