/*
 * Project: dp-jal
 * File:	ImageFactory.java
 * Package: com.ospreydcs.dp.jal.tools.common.datagen.values
 * Type: 	ImageFactory
 *
 * Copyright 2010-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * @author Christopher K. Allen
 * @org    OspreyDCS
 * @since Nov 14, 2025
 *
 */
package com.ospreydcs.dp.jal.tools.common.datagen.values;

import java.time.Instant;

import com.ospreydcs.dp.jal.common.BufferedImage;
import com.ospreydcs.dp.jal.common.DpSupportedType;
import com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory;
import com.ospreydcs.dp.jal.tools.common.datagen.JalComplexType;
import com.ospreydcs.dp.jal.tools.common.datagen.JalScalarType;
import com.ospreydcs.dp.jal.tools.config.JalToolsConfig;
import com.ospreydcs.dp.jal.tools.config.datagen.values.JalToolsImageValuesConfig;

/**
 * <p>
 * Class that generates simulated images of type <code>{@link BufferedImage}</code> JAL Library.
 * </p>
 * <p>
 * Instances of this class are factories of <code>{@link BufferedImage}</code> instances.
 * The type <code>{@link BufferedImage}</code> within the Data Platform Java API Library (JAL)
 * is compatible with the Data Platform <code>Image</code> Protocol Buffers message.  That is, 
 * instances of one type can be used to populate instances of the other.  
 * </p>
 * <p>
 * <h2>Image Data</h2>
 * The <code>BufferedImage</code> objects generated by an <code>ImageFactory</code> instance contain 
 * only noise. The actual image pixels are simply the random values of heap memory allocated at the time
 * of image creation.  This is the fasted method of simulated image production available.
 * </p> 
 * <p>
 * <h2>Image Formats</h2>
 * The image format is determined by the <code>{@link BufferedImage.Format}</code> enumeration.  For simulated
 * images the format is essentially academic since the generated image data are simply noise, thus, it is
 * irrelevant how the image data is interpreted.  However, the image format parameter is still attached to
 * the generated images. 
 * <p>
 * <h2>Image Names</h2>
 * All images are named within the Data Platform archive.  Thus, all <code>BufferedImage</code> instances
 * have a 'name' attribute.  Objects of class <code>ImageFactory</code> create names for the generated images
 * by prepending a 'name prefix' to the current image count.  The name prefix and the image count are
 * delimited by the default value given in the JAL Tools configuration and contained in class constant
 * <code>{@link #STR_SEP_DEF}</code> = {@value #STR_SEP_DEF}.  Thus, image names have the format
 * <code>
 * <pre>
 *   strNmPref + {@link #STR_SEP_DEF} + cntImages
 * </pre>
 * </code>
 * where
 * <ul>
 * <li><code>strNmPref</code> is the name prefix given at creation/construction (or default value),</li>
 * <li><code>cntImages</code> is the current image number created by the <code>ImageFactory</code> instance.</li>
 * </ul>
 * Note that all images generated by a single <code>ImageFactory</code> instance have unique names.  However,
 * the image names across <code>ImageFactory</code> instances are not necessary unique, specifically, if multiple
 * <code>ImageFactory</code> instances are configured with the same image name prefix.
 * </p>
 * <p>
 * <h2>Image Timestamps</h2>
 * Each <code>BufferedImage</code> instance has a timestamp attribute (i.e., <code>{@link BufferedImage#getTimestamp()}</code>.
 * Within <code>ImageFactory</code> objects image timestamps are generated at the instant of creation, that is, at
 * the time of method <code>{@link #nextDatum()}</code> invocation.  This image attribute can be used to create
 * image uniqueness even if image names are not unique across multiple <code>ImageFactory</code> image generators.
 * Note that, currently, there is not configuration for timestamp assignment. 
 * </p>
 *
 * @author Christopher K. Allen
 * @since Nov 14, 2025
 *
 */
public class ImageFactory implements IDatumFactory {

    
    //
    // Creators
    //
    
    /**
     * <p>
     * Creates and returns a new <code>ImageFactory</code> instance configured by the given arguments.
     * </p>
     * <p>
     * The returned <code>ImageFactory</code> instance creates images of type <code>{@link BufferedImage}</code>.
     * The <code>BufferedImage</code> type is compatible with the Data Platform <code>Image</code> Protocol
     * Buffers message for transport to and from the Data Platform archive.
     * </p>
     * <p>
     * Note that any images produced by the returned <code>ImageFactory</code> are noise, image data is
     * simply allocated from the heap and not processed.  See the class documentation <code>{@link ImageFactory}</code>
     * for more information.
     * </p>
     * <p>
     * <h2>Default Values</h2>
     * This method uses JAL Tools configuration default values for missing constructor arguments in 
     * <code>{@link #ImageFactory(int, com.ospreydcs.dp.jal.common.BufferedImage.Format, String)}</code>.
     * <br/>
     * <br/>
     * <ul>
     * <li>name prefix = <code>{@link #STR_NM_PREF_DEF}</code> = {@value #STR_NM_PREF_DEF}.</li>
     * <li>format = <code>{@link #ENM_FMT_DEF}</code> = {@value #ENM_FMT_DEF}.</li>
     * </ul>
     * </p> 
     * 
     * @param szAlloc   size (in bytes) of all generated images
     * @param enmFormat the format of all generated images
     * 
     * @return  a new <code>ImageFactory</code> instance ready for image generation
     */
    public static ImageFactory  from(int szAlloc) {
        return ImageFactory.from(szAlloc, ENM_FMT_DEF, STR_NM_PREF_DEF);
    }
    
    /**
     * <p>
     * Creates and returns a new <code>ImageFactory</code> instance configured by the given arguments.
     * </p>
     * <p>
     * The returned <code>ImageFactory</code> instance creates images of type <code>{@link BufferedImage}</code>.
     * The <code>BufferedImage</code> type is compatible with the Data Platform <code>Image</code> Protocol
     * Buffers message for transport to and from the Data Platform archive.
     * </p>
     * <p>
     * Note that any images produced by the returned <code>ImageFactory</code> are noise, image data is
     * simply allocated from the heap and not processed.  See the class documentation <code>{@link ImageFactory}</code>
     * for more information.
     * </p>
     * <p>
     * <h2>Default Values</h2>
     * This method uses JAL Tools configuration default values for missing constructor arguments in 
     * <code>{@link #ImageFactory(int, com.ospreydcs.dp.jal.common.BufferedImage.Format, String)}</code>.
     * <br/>
     * <br/>
     * <ul>
     * <li>name prefix = <code>{@link #STR_NM_PREF_DEF}</code> = {@value #STR_NM_PREF_DEF}.</li>
     * </ul>
     * </p> 
     * 
     * @param szAlloc   size (in bytes) of all generated images
     * @param enmFormat the format of all generated images
     * 
     * @return  a new <code>ImageFactory</code> instance ready for image generation
     */
    public static ImageFactory  from(int szAlloc, BufferedImage.Format enmFormat) {
        return ImageFactory.from(szAlloc, enmFormat, STR_NM_PREF_DEF);
    }
    
    /**
     * <p>
     * Creates and returns a new <code>ImageFactory</code> instance configured by the given arguments.
     * </p>
     * <p>
     * The returned <code>ImageFactory</code> instance creates images of type <code>{@link BufferedImage}</code>.
     * The <code>BufferedImage</code> type is compatible with the Data Platform <code>Image</code> Protocol
     * Buffers message for transport to and from the Data Platform archive.
     * </p>
     * <p>
     * Note that any images produced by the returned <code>ImageFactory</code> are noise, image data is
     * simply allocated from the heap and not processed.  See the class documentation <code>{@link ImageFactory}</code>
     * for more information.
     * </p>
     * 
     * @param szAlloc   size (in bytes) of all generated images
     * @param enmFormat the format of all generated images
     * @param strNmPref the name prefix given to all generated images (suffixed by image count)
     * 
     * @return  a new <code>ImageFactory</code> instance ready for image generation
     */
    public static ImageFactory  from(int szAlloc, BufferedImage.Format enmFormat, String strNmPref) {
        return new ImageFactory(szAlloc, enmFormat, strNmPref);
    }
    
    
    // 
    // JAL Tools Resources
    //
    
    /** Default image generation parameters */
    private static final JalToolsImageValuesConfig  CFG_DEF = JalToolsConfig.getInstance().datagen.values.image;
    
    
    //
    // Class Constants - Default Values
    //
    
    /** The default value for image name prefixes */
    public static final String                  STR_NM_PREF_DEF = CFG_DEF.namePrefix;
    
    /** The separator between image name prefix and image count */
    public static final String                  STR_SEP_DEF = CFG_DEF.separator;
    
    /** The default value for image format */
    public static final BufferedImage.Format    ENM_FMT_DEF = CFG_DEF.format;
    
    
    //
    // Class Constants 
    //
    
    /** The value type for simulated data generated by this data factory */
    public static final DpSupportedType     ENM_DATUM_TYPE = DpSupportedType.IMAGE;
    
    /** The scalar type of all data produced by this data factory */
    public static final JalScalarType       ENM_SCALAR_TYPE = JalScalarType.UNSUPPORTED;
    
    /** The complex type of all data produced by this data factory */
    public static final JalComplexType       ENM_CMPLX_TYPE = JalComplexType.IMAGE;
    
    
    //
    // Configuration
    //
    
    /** Image size, that is, memory allocation */
    private final int                   szAlloc;
    
    /** Image format enumeration */
    private final BufferedImage.Format  enmFormat;
    
    /** Image name prefix */
    private final String                strNmPref;
    
    
    //
    // State Variables
    //
    
    /** Image counter - used for image name generation */
    private int         cntImages = 0;
    
    
    //
    // Constructor
    //
    
    /**
     * <p>
     * Constructs a new <code>ImageFactory</code> instance.
     * </p>
     *
     * @param szAlloc   size (in bytes) of all generated images
     * @param enmFormat the format of all generated images
     * @param strNmPref the name prefix given to all generated images (suffixed by image count)
     */
    public ImageFactory(int szAlloc, BufferedImage.Format enmFormat, String strNmPref) {
        this.szAlloc = szAlloc;
        this.enmFormat = enmFormat;
        this.strNmPref = strNmPref;
        
        this.cntImages = 0;
    }

    //
    // Configuration
    //
    
    /**
     * <p>
     * Returns the size (in bytes) of all images generated by this factory.
     * </p>
     * <p>
     * The returned value is the size of the image data buffer in the <code>BufferedImage</code> class.
     * This is a configuration parameter provided at creation/construction.
     * </p>
     * 
     * @return  image data size (in bytes) of all images produced by this factory
     */
    public int  getSize() {
        return this.szAlloc;
    }
    
    /**
     * <p>
     * Returns the format of all images generated by this factory.
     * </p>
     * <p>
     * This is a configuration parameter provided at creation/construction; it can have a default
     * value if not explicitly provided.
     * </p>
     * 
     * @return  the image format of all generated images as identified by the <code>{@link BufferedImage.Format}</code> constant
     */
    public BufferedImage.Format getFormat() {
        return this.enmFormat;
    }
    
    /**
     * <p>
     * Returns the string prefix given to all image names produced by this factory.
     * </p>
     * <p>
     * All image names are generated by prepending the returned prefix to the current image count.  Thus,
     * all images generated by this factory have unique names, however, uniqueness may not be shared across
     * factories if the same prefix is used.
     * This is a configuration parameter provided at creation/construction; it can have a default
     * value if not explicitly provided.
     * </p>
     * 
     * @return  the string prefix used in all names for images generated by the factory
     */
    public String   getNamePrefix() {
        return this.strNmPref;
    }
    
    
    //
    // IDatumFactory Interface
    //
    
    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory#getDatumType()
     */
    @Override
    public DpSupportedType  getDatumType() {
        return ENM_DATUM_TYPE;
    }
    
    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory#getScalarType()
     */
    @Override
    public JalScalarType getScalarType() {
        return ENM_SCALAR_TYPE;
    }

    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory#getComplexType()
     */
    @Override
    public JalComplexType getComplexType() {
        return ENM_CMPLX_TYPE;
    }

    /**
     * <p>
     * Creates a new image value in the sequence of images.
     * </p>
     * <p>
     * The returned image type is <code>{@link BufferedImage}</code>.  The image name is given by
     * the image name prefix provided at creation/construction appended with the current image count.
     * The image timestamp is given by the instant of this method invocation.  The image data is
     * random, simply the values within heap memory allocated for the data attribute.
     * The image format is that provided at creation/construction.
     * </p> 
     *
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory#nextDatum()
     * @see ImageFactory
     */
    @Override
    public Object nextDatum() {
        
        // Create a new image with empty data vector (raw allocation)
        String  strName = this.strNmPref + STR_SEP_DEF + Integer.toString(this.cntImages);
        Instant insTms = Instant.now();
        byte[]  arrData = new byte[this.szAlloc];
        
        BufferedImage   image = new BufferedImage(strName, insTms, this.enmFormat, arrData);
        
        // Increment image counter then return image
        this.cntImages++;
        
        return image;
    }

}
