/*
 * Project: dp-jal
 * File:	StructureFactory.java
 * Package: com.ospreydcs.dp.jal.tools.common.datagen.values
 * Type: 	StructureFactory
 *
 * Copyright 2010-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * @author Christopher K. Allen
 * @org    OspreyDCS
 * @since Nov 13, 2025
 *
 */
package com.ospreydcs.dp.jal.tools.common.datagen.values;

import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

import com.ospreydcs.dp.jal.common.DpSupportedType;
import com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory;
import com.ospreydcs.dp.jal.tools.common.datagen.JalComplexType;
import com.ospreydcs.dp.jal.tools.common.datagen.JalScalarType;
import com.ospreydcs.dp.jal.tools.config.JalToolsConfig;
import com.ospreydcs.dp.jal.tools.config.datagen.values.JalToolsStructValuesConfig;

/**
 * <p>
 * Creates Data Platform compatible structures of simulated data suitable for populating a <code>Structure</code> Protocol Buffers message.
 * </p>
 * <p>
 * Factory of data structures containing artificial data with <code>{@link #intFanOut}</code>
 * fields at each level, each field having the same number of sub-fields, up to a depth of
 * <code>{@link #intDepth}</code>.  Thus, all generated data structures have a very specific format.
 * </p>
 * <p>
 * The generated structures are essentially symmetric trees with each node containing the same number
 * of sub-nodes (sub-fields) given by the fan-out, including the root node.
 * Thus, the field values within each structure are sub-structures for all but the last level where
 * node values are scalars, with type given by the <code>{@link ScalarFactory}</code> provided construction.  
 * Thus, this structure factory class produces sub-structures within a generated structure.
 * </p>
 * <p>
 * Internally, structure creation uses recursion to create a tree structure which expands
 * geometrically.  Thus, be cautious when specifying configuration parameters 
 * <code>depth</code> and <code>fanout</code>. 
 * </p>
 * <p>
 * <h2>Structure Format</h2>
 * As mentioned above all generated structure instances have a symmetric tree format.
 * The tree depth is given by the <code>depth</code> parameter, which  is the number of tree "levels."  
 * Each node has <code>fanout</code> sub-nodes up to depth <code>depth</code>, that is, up to the terminal
 * nodes.  The terminal nodes have scalar values as field values.
 * </p>
 * <h2>Structure Type</h2>
 * The Java type of all generated structure instances is <code>Map&lt;String, Object&gt;</code>.  The map represents
 * (name, value) pairs where each pair is a node in the structure.  The 'name' element is the field name of the node
 * and the 'value' element is the value at that node.  The 'value' is a Java <code>Object</code> and its type depends
 * both upon the location of the node in the tree structure and the <code>ScalarFactory</code> instance provided at
 * construction/creation.
 * <ul>
 * <li>level < depth: value = <code>Map&lt;String, Object&gt;</code> sub-tree for node.</li>
 * <li>level = depth: value = <code>{@link ScalarFactory#nextDatum()}</code>.</li>
 * </ul>
 * The field names are generated by node depth and fan-out position with separators and prefixes defined
 * in the JAL Tools default configuration.
 * </p>
 * <p>
 * <h2>Unique Field Names</h2>
 * Each generated structure has the same format but different field values. That is, they are identical in node structure 
 * but their field values differ.  Additionally, the field names are unique within a structure instance but identical
 * across different structures.  Thus, different structure instances have the same field names in the same node locations.
 * </p>
 * <p>
 * It is sometimes desirable to have completely different field names across all generated structure instances.  These
 * use cases generally occur in testing scenarios where storage of structures is being evaluated.  The unique field
 * names are achieved by prefixing field names with the structure instance index. 
 * <br/>
 * <b>NOTE:</b>: Field names are only unique across structures generated by a single <code>StructureFactory</code>
 * instance.  Multiple instances of <code>StructureFactory</code> will generate the same "unique field names" for
 * the same structure count (i.e., the nth structure generated by factory instance 1 will have the same names as
 * the nth structure generated by factory instance 2).  
 * </p>
 * <p>
 * <h2>Structure Size and Allocation</h2>
 * The structure is a tree with each node containing 
 * <i>F</i> = <code>{@link #intFanOut}</code> branches.  Each branch 
 * contains another tree with the same structure, except for the terminating 
 * branch. The depth <i>D</i> of the tree is given by 
 * <pre>
 *   <i>D</i> = <code>cntDepth</code>
 * </pre>
 * where <code>cntDepth</code> is a constructor argument value.  The final branch 
 * contains fields with generated scalar values as specified at construction.
 * </p>
 * <h2>WARNING:</h2>
 * <p>
 * Because of the nature of the returned tree structure, its total size grows 
 * geometrically (approximately exponential).  
 * For a structure with <i>F</i> fields per node and with a depth <i>D</i>, 
 * the number <i>n</i> of <code>Double</code> values contained in the final 
 * branch is given by
 * <pre>
 *     <i>n</i> = <i>F</i><sup><i>D</i></sup>
 * </pre>
 * However, the total number of nodes <i>N</i>(<i>D</i>) to a depth <i>D</i> 
 * in the tree is given by the 
 * following:
 * <pre>
 *     <i>N</i>(<i>D</i>) = 1 + <i>F</i> + <i>F</i><sup>2</sup> + &hellip; + <i>F<sup>D</sup></i>
 *     
 *          = (<i>F</i><sup><i>D</i>+1</sup> - 1)/(<i>F</i> - 1)
 *          &asymp; <i>F</i><sup><i>D</i>+1</sup>/(<i>F</i> - 1)
 * </pre>
 * Thus, for example, a structure with <i>F</i> = 5 fields and depth <i>D</i> = 3
 * the number <i>n</i> of doubles in the final branch is 
 * <i>n</i> = 5<sup>3</sup> = 125
 * while the total number of nodes <i>N</i> is given by 
 * <i>N</i> = (5<sup>4</sup> - 1)/4 = 156.
 * <br/>
 * <br/> 
 * However, a structure with <i>F</i> = 5 fields and depth <i>D</i> = 5
 * the number <i>n</i> of doubles in the final branch is 
 * <i>n</i> = 5<sup>5</sup> = 3,125
 * while the total number of nodes <i>N</i> is given by 
 * <i>N</i> = (5<sup>6</sup> - 1)/4 = 3,906.
 * </p>
 * <p>
 * Let <i>A<sub>m</sub></i> be the allocation for a map and <i>A<sub>t</sub></i>
 * be the allocation per end node. Then the total allocation will be
 * <pre>
 *     <i>A</i><sub>tot</sub> = <i>N</i>(<i>D</i>-1)&times;<i>F</i>&times;<i>A<sub>m</sub></i> + <i>F</i><sup><i>D</i></sup>&times;<i>A<sub>t</sub></i>
 *          &asymp; <i>A</i>(2<i>F<sup>D</i>+1</sup> - <i>F<sup>D</sup></i> - <i>F</i>)/(<i>F</i> -  1)
 *          &asymp; 2<i>A</i><i>F</i><sup><i>D</i>+1</sup>/(<i>F</i> - 1)
 * </pre>
 * where <i>A<sub>tot</sub></i> is the total allocation. The first line
 * consists of the sum of the allocation for the internal nodes (each containing
 * <i>F</i> maps) and the terminal nodes.  In the second line we have 
 * assumed the approximation 
 * <i>A</i> &asymp; <i>A<sub>m</sub></i> &asymp; <i>A<sub>t</sub></i>, where
 * <i>A</i> is the average allocation.  The third line makes use of the 
 * inequality
 * 1/<i>F</i><sup><i>D</i>-1</sup> &lt;&lt; 1, and the inequality
 * 1 &lt;&lt; 2<i>F</i>.
 * </p>
 * <p>
 * The following table is provided to help design frame factory configuration
 * files.  There are example structure configurations producing memory allocations
 * of several different orders of magnitude.
 * </p>
 * <p>
 * <table>
 *   <tr>
 *     <th><i>F</i> (fan-out)</th>
 *     <th><i>D</i> (depth) </th>
 *     <th><i>n</i> (branches final)</th>
 *     <th><i>N</i> (nodes total)</th>
 *     <th>~Memory (bytes)</th>
 *   </tr>
 *   <tr>
 *     <td>4</td>
 *     <td>2</td>
 *     <td>16</td>
 *     <td>21</td>
 *     <td>1,575</td>
 *   </tr>
 *   <tr>
 *     <td>5</td>
 *     <td>2</td>
 *     <td>25</td>
 *     <td>31</td>
 *     <td>2,325</td>
 *   </tr>
 *   <tr>
 *     <td>5</td>
 *     <td>3</td>
 *     <td>125</td>
 *     <td>156</td>
 *     <td>11,700</td>
 *   </tr>
 *   <tr>
 *     <td>5</td>
 *     <td>5</td>
 *     <td>3,125</td>
 *     <td>3,906</td>
 *     <td>292,950</td>
 *   </tr>
 *   <tr>
 *     <td>5</td>
 *     <td>6</td>
 *     <td>15,625</td>
 *     <td>19,531</td>
 *     <td>1,464,825</td>
 *   </tr>
 *   <tr>
 *     <td>5</td>
 *     <td>7</td>
 *     <td>78,125</td>
 *     <td>97,656</td>
 *     <td>7,324,200</td>
 *   </tr>
 *   <tr>
 *     <td>7</td>
 *     <td>2</td>
 *     <td>49</td>
 *     <td>57</td>
 *     <td>4,275</td>
 *   </tr>
 *   <tr>
 *     <td>7</td>
 *     <td>3</td>
 *     <td>343</td>
 *     <td>400</td>
 *     <td>30,000</td>
 *   </tr>
 *   <tr>
 *     <td>7</td>
 *     <td>4</td>
 *     <td>2,401</td>
 *     <td>2,801</td>
 *     <td>201,075</td>
 *   </tr>
 *   <tr>
 *     <td>7</td>
 *     <td>5</td>
 *     <td>16,807</td>
 *     <td>19,608</td>
 *     <td>1,470,600</td>
 *   </tr>
 *   <tr>
 *     <td>10</td>
 *     <td>3</td>
 *     <td>1,00</td>
 *     <td>1,111</td>
 *     <td>83,325</td>
 *   </tr>
 *   <tr>
 *     <td>10</td>
 *     <td>4</td>
 *     <td>10,000</td>
 *     <td>11,111</td>
 *     <td>833,325</td>
 *   </tr>
 *   <tr>
 *     <td>10</td>
 *     <td>5</td>
 *     <td>100,00</td>
 *     <td>111,111</td>
 *     <td>8,333,325</td>
 *   </tr>
 *   <tr>
 *     <td>10</td>
 *     <td>6</td>
 *     <td>1,000,000</td>
 *     <td>1,111,111</td>
 *     <td>83,333,325</td>
 *   </tr>
 *   <caption>Tree Structure Allocations</caption>
 * </table>
 * </p>  
 * <p>
 * The memory allocation is an (under-)estimate using 85for
 * terminal each node. This value is the approximate size of a <code>Double</code> plus a 15-character
 * string.  The internal node allocation must be multiplied by <i>F</i>
 * since there are <i>F</i> such entries. 
 * (Note this estimate does not include the allocation for the map container.)
 * </p>
 *
 *
 * @author Christopher K. Allen
 * @since Nov 13, 2025
 *
 */
public class StructureFactory implements IDatumFactory {

    
    //
    // Creators
    //

    /**
     * <p>
     * Creates and returns a new <code>{@link StructureFactory}</code> instance configured according to the given arguments.
     * </p>
     * <p>
     * The returns structure factory produces symmetric tree structures with the given depth and node fan-out.  The
     * Java type of the produced tree structures is <code>Map&lt;String, Object&gt;</code> which is a container of
     * (name, value) pairs for each tree node.  The 'name' element is the tree-structure field name and the 'value'
     * element is the tree-structure field value (potentially another sub-structure).  
     * </p>
     * <p>
     * <h2>Field Values</h2>
     * All field values are sub-structures
     * until the final depth is reach, that is the "terminal level".  At the terminal level all field value are produced 
     * using the <code>{@link ScalarFactory}</code> instance provided in the argument list.  
     * See the <code>{@link StructureFactory}</code> class documentation for further explanations of the generated tree 
     * structures and their relationship to the given argument values.
     * </p>
     * <p>
     * <h2>Field Names</h2>
     * Tree structure field names are generation according to the node index within the tree, prefixed by the value
     * of class constant <code>{@link #STR_FLD_NM_PREF}</code> = {@value #STR_FLD_NM_PREF}.
     * Node indices are determined by depth and fan-out with values separated by the value of 
     * <code>{@link #STR_FLD_NM_SEP}</code> = {@value #STR_FLD_NM_SEP}.
     * </p>
     * <p>
     * <h2>Unique Field Names</h2>
     * It is possible to generate tree structures with all unique field name (otherwise each structure instance will
     * have the same field name at each corresponding node position)
     * Unique field names are created by prepending the generated structure count all field names.
     * The structure count is prefixed by the class constant 
     * <code>{@link #STR_UNIQ_FLD_NM_PREF}</code> = {@value #STR_UNIQ_FLD_NM_PREF}.    
     * For <code>StructureFactory</code> instance returned by this method, 
     * the creation of unique field names for all generated tree structure instances is determined by the JAL Tools
     * default configuration and held in class constant <code>{@link #BOL_UNIQ_FLD_NM_ENBL_DEF}</code>.  The value
     * at the time of document generation is 
     * <code>{@link #BOL_UNIQ_FLD_NM_ENBL_DEF}</code> = {@value #BOL_UNIQ_FLD_NM_ENBL_DEF}. 
     * </p> 
     * 
     * @param depth         node depth of the tree structure
     * @param fanout        node fan-out at each sub-tree 
     * @param recCfgFac     configuration record for scalar value factory generating terminal node values
     * 
     * @return  a new <code>StructureFactory</code> instance ready for tree structure instance generation
     * 
     * @throws  IllegalArgumentException    depth and fan-out must both be greater than 1, scalar factory cannot be null 
     */
    public static StructureFactory  from(int depth, int fanout, ScalarFactorySpec recCfgFac) throws IllegalArgumentException {
        return StructureFactory.from(depth, fanout, BOL_UNIQ_FLD_NM_ENBL_DEF, recCfgFac);   // throws IllegalArgumentException
    }
    
    /**
     * <p>
     * Creates and returns a new <code>{@link StructureFactory}</code> instance configured according to the given arguments.
     * </p>
     * <p>
     * The returns structure factory produces symmetric tree structures with the given depth and node fan-out.  The
     * Java type of the produced tree structures is <code>Map&lt;String, Object&gt;</code> which is a container of
     * (name, value) pairs for each tree node.  The 'name' element is the tree-structure field name and the 'value'
     * element is the tree-structure field value (potentially another sub-structure).  
     * </p>
     * <h2>Field Values</h2>
     * All field values are sub-structures
     * until the final depth is reach, that is the "terminal level".  At the terminal level all field value are produced 
     * using the <code>{@link ScalarFactory}</code> instance provided in the argument list.  
     * See the <code>{@link StructureFactory}</code> class documentation for further explanations of the generated tree 
     * structures and their relationship to the given argument values.
     * </p>
     * <p>
     * <h2>Field Names</h2>
     * Tree structure field names are generation according to the node index within the tree, prefixed by the value
     * of class constant <code>{@link #STR_FLD_NM_PREF}</code> = {@value #STR_FLD_NM_PREF}.
     * Node indices are determined by depth and fan-out with values separated by the value of 
     * <code>{@link #STR_FLD_NM_SEP}</code> = {@value #STR_FLD_NM_SEP}.
     * </p>
     * <p>
     * <h2>Unique Field Names</h2>
     * It is possible to generate tree structures with all unique field name (otherwise each structure instance will
     * have the same field name at each corresponding node position)
     * Unique field names are created by prepending the generated structure count all field names.
     * The structure count is prefixed by the class constant 
     * <code>{@link #STR_UNIQ_FLD_NM_PREF}</code> = {@value #STR_UNIQ_FLD_NM_PREF}.    
     * For <code>StructureFactory</code> instance returned by this method, 
     * the creation of unique field names for all generated tree structure instances is determined by the 
     * <code>boolean</code> argument. 
     * </p> 
     * 
     * @param depth         node depth of the tree structure
     * @param fanout        node fan-out at each sub-tree 
     * @param bolUniqFldNms enable/disable unique field names for all generated tree structures
     * @param recFacSpec    configuration specification for scalar value factory generating terminal node values
     * 
     * @return  a new <code>StructureFactory</code> instance ready for tree structure instance generation
     * 
     * @throws  IllegalArgumentException    depth and fan-out must both be greater than 1, scalar factory cannot be null 
     */
    public static StructureFactory  from(int depth, int fanout, boolean uniqFldNms, ScalarFactorySpec recFacSpec) throws IllegalArgumentException {
        ScalarFactory   facValues = recFacSpec.newFactory();
        
        return StructureFactory.from(depth, fanout, uniqFldNms, facValues);      // throws IllegalArgumentException
    }
    
    /**
     * <p>
     * Creates and returns a new <code>{@link StructureFactory}</code> instance configured according to the given arguments.
     * </p>
     * <p>
     * The returns structure factory produces symmetric tree structures with the given depth and node fan-out.  The
     * Java type of the produced tree structures is <code>Map&lt;String, Object&gt;</code> which is a container of
     * (name, value) pairs for each tree node.  The 'name' element is the tree-structure field name and the 'value'
     * element is the tree-structure field value (potentially another sub-structure).  
     * </p>
     * <p>
     * <h2>Field Values</h2>
     * All field values are sub-structures
     * until the final depth is reach, that is the "terminal level".  At the terminal level all field value are produced 
     * using the <code>{@link ScalarFactory}</code> instance provided in the argument list.  
     * See the <code>{@link StructureFactory}</code> class documentation for further explanations of the generated tree 
     * structures and their relationship to the given argument values.
     * </p>
     * <p>
     * <h2>Field Names</h2>
     * Tree structure field names are generation according to the node index within the tree, prefixed by the value
     * of class constant <code>{@link #STR_FLD_NM_PREF}</code> = {@value #STR_FLD_NM_PREF}.
     * Node indices are determined by depth and fan-out with values separated by the value of 
     * <code>{@link #STR_FLD_NM_SEP}</code> = {@value #STR_FLD_NM_SEP}.
     * </p>
     * <p>
     * <h2>Unique Field Names</h2>
     * It is possible to generate tree structures with all unique field name (otherwise each structure instance will
     * have the same field name at each corresponding node position)
     * Unique field names are created by prepending the generated structure count all field names.
     * The structure count is prefixed by the class constant 
     * <code>{@link #STR_UNIQ_FLD_NM_PREF}</code> = {@value #STR_UNIQ_FLD_NM_PREF}.    
     * For <code>StructureFactory</code> instance returned by this method, 
     * the creation of unique field names for all generated tree structure instances is determined by the JAL Tools
     * default configuration and held in class constant <code>{@link #BOL_UNIQ_FLD_NM_ENBL_DEF}</code>.  The value
     * at the time of document generation is 
     * <code>{@link #BOL_UNIQ_FLD_NM_ENBL_DEF}</code> = {@value #BOL_UNIQ_FLD_NM_ENBL_DEF}. 
     * </p> 
     * 
     * @param depth         node depth of the tree structure
     * @param fanout        node fan-out at each sub-tree 
     * @param facValues     scalar value factory for terminal node values
     * 
     * @return  a new <code>StructureFactory</code> instance ready for tree structure instance generation
     * 
     * @throws  IllegalArgumentException    depth and fan-out must both be greater than 1, scalar factory cannot be null 
     */
    public static StructureFactory  from(int depth, int fanout, ScalarFactory facValues) throws IllegalArgumentException {
        return StructureFactory.from(depth, fanout, BOL_UNIQ_FLD_NM_ENBL_DEF, facValues);   // throws IllegalArgumentException
    }
    
    /**
     * <p>
     * Creates and returns a new <code>{@link StructureFactory}</code> instance configured according to the given arguments.
     * </p>
     * <p>
     * The returns structure factory produces symmetric tree structures with the given depth and node fan-out.  The
     * Java type of the produced tree structures is <code>Map&lt;String, Object&gt;</code> which is a container of
     * (name, value) pairs for each tree node.  The 'name' element is the tree-structure field name and the 'value'
     * element is the tree-structure field value (potentially another sub-structure).  
     * </p>
     * <h2>Field Values</h2>
     * All field values are sub-structures
     * until the final depth is reach, that is the "terminal level".  At the terminal level all field value are produced 
     * using the <code>{@link ScalarFactory}</code> instance provided in the argument list.  
     * See the <code>{@link StructureFactory}</code> class documentation for further explanations of the generated tree 
     * structures and their relationship to the given argument values.
     * </p>
     * <p>
     * <h2>Field Names</h2>
     * Tree structure field names are generation according to the node index within the tree, prefixed by the value
     * of class constant <code>{@link #STR_FLD_NM_PREF}</code> = {@value #STR_FLD_NM_PREF}.
     * Node indices are determined by depth and fan-out with values separated by the value of 
     * <code>{@link #STR_FLD_NM_SEP}</code> = {@value #STR_FLD_NM_SEP}.
     * </p>
     * <p>
     * <h2>Unique Field Names</h2>
     * It is possible to generate tree structures with all unique field name (otherwise each structure instance will
     * have the same field name at each corresponding node position)
     * Unique field names are created by prepending the generated structure count all field names.
     * The structure count is prefixed by the class constant 
     * <code>{@link #STR_UNIQ_FLD_NM_PREF}</code> = {@value #STR_UNIQ_FLD_NM_PREF}.    
     * For <code>StructureFactory</code> instance returned by this method, 
     * the creation of unique field names for all generated tree structure instances is determined by the 
     * <code>boolean</code> argument. 
     * </p> 
     * 
     * @param depth         node depth of the tree structure
     * @param fanout        node fan-out at each sub-tree 
     * @param bolUniqFldNms enable/disable unique field names for all generated tree structures
     * @param facValues     scalar value factory for terminal node values
     * 
     * @return  a new <code>StructureFactory</code> instance ready for tree structure instance generation
     * 
     * @throws  IllegalArgumentException    depth and fan-out must both be greater than 1, scalar factory cannot be null 
     */
    public static StructureFactory  from(int depth, int fanout, boolean uniqFldNms, ScalarFactory facValues) throws IllegalArgumentException {
        return new StructureFactory(depth, fanout, uniqFldNms, facValues);      // throws IllegalArgumentException
    }
    

    //
    // Tools Library Resources
    //
    
    /** The default parameters used for structure instance creation - NOTE - all field name parameters are taken from here */
    private static final JalToolsStructValuesConfig     CFG_DEF = JalToolsConfig.getInstance().datagen.values.structure;

    
    //
    // Class Constants
    //
    
    /** Enable/disable unique field name generation default configuration */
    public static final boolean BOL_UNIQ_FLD_NM_ENBL_DEF = CFG_DEF.fieldNames.unique.enabled;
    

    /** Prefix added to all structure field names */
    public static final String STR_FLD_NM_PREF = CFG_DEF.fieldNames.prefix;

    /** Separator used within field names */
    public static final String STR_FLD_NM_SEP = CFG_DEF.fieldNames.separator;

    
    /** Unique field name prefix - added to field names when unique field names are specified */
    public static final String STR_UNIQ_FLD_NM_PREF = CFG_DEF.fieldNames.unique.prefix;

    /** Unique field name prefix separator */
    public static final String STR_UNIQ_FLD_NM_SEP_STRUCT_IND = CFG_DEF.fieldNames.unique.separator1;
    
    /** Unique field name prefix separator */
    public static final String STR_UNIQ_FLD_NM_SEP_PREF_TO_NM = CFG_DEF.fieldNames.unique.separator2;
    

    /** Datum value type of all simulated data produced by this data value factory */
    public static final DpSupportedType     ENM_DATUM_TYPE = DpSupportedType.STRUCTURE;
    
    /** Complex value type of all simulated data produced by this data value factory */
    public static final JalComplexType       ENM_CMPLX_TYPE = JalComplexType.STRUCTURE;
    
    
    //
    // Resources
    //
    
    /** Generator of scalar field values */
    private final ScalarFactory facValues;
    
    
    //
    // Configuration
    //
    
    /** The depth of each (tree) structure produced */
    private final int       intDepth;
    
    /** The current number of sub-fields per field (node) */
    private final int       intFanOut;
    
    /** Create unique field names flag */
    private final boolean   bolUniqFldNms;
    

    //
    // State Variables
    //
    
    /** Counter of generated structures - used for unique naming of structure fields */
    private int         cntStructs = 0;
    
    
    //
    // Constructors
    //
    
    /**
     * <p>
     * Constructs a new <code>StructureFactory</code> instance configured with the given arguments.
     * </p>
     *
     * @param depth         node depth of the tree structure
     * @param fanout        node fan-out at each sub-tree 
     * @param bolUniqFldNms enable/disable unique field names for all generated tree structures
     * @param facValues     scalar value factory for terminal node values
     * 
     * @throws  IllegalArgumentException    depth and fan-out must both be greater than 1, scalar factory cannot be null 
     */
    public StructureFactory(int depth, int fanout, boolean bolUniqFldNms, ScalarFactory facValues) throws IllegalArgumentException {

        // Check arguments
        if (depth < 1)
            throw new IllegalArgumentException("Argument depth = " + depth + " must be > 0.");
        if (fanout < 1)
            throw new IllegalArgumentException("Argument fanout = " + fanout + " must be > 0.");
        if (facValues == null)
            throw new IllegalArgumentException("Argument facValue = " + facValues);
        
        this.intDepth = depth;
        this.intFanOut = fanout;
        this.bolUniqFldNms = bolUniqFldNms;
        this.facValues = facValues;
    }

    
    //
    // Configuration
    //
    
    /**
     * <p>
     * Determines whether or not terminal-level field values within structures are generated 
     * randomly (i.e., using a random number generator).
     * </p>
     * 
     * @return  <code>true</code> the terminal field values are generated randomly,
     *          <code>false</code> the terminal field values are generated incrementally
     */
    public boolean      hasRandomValues() {
        return this.facValues.isRandom();
    }
    
    /**
     * <p>
     * Determines whether or not the unique field name feature is enabled.
     * </p>
     * 
     * @return  <code>true</code> if all generated structures have unique field names,
     *          <code>false</code> all generated structures have the same field names
     */
    public boolean      hasUniqueFieldNames() {
        return this.bolUniqFldNms;
    }
    
    /**
     * <p>
     * Returns the depth of structures generated, that is, the number of structure levels.
     * </p>
     * 
     * @return  number of levels for each generated structure 
     */
    public int  getDepth() {
        return this.intDepth;
    }
    
    /**
     * <p>
     * Returns the number sub-fields per structure field, including root node.
     * </p>
     * <p>
     * This is equivalent to the fan out of a tree graph, which is constant in this case.
     * </p> 
     * 
     * @return  number of fields contained in each tree-structure node
     */
    public int  getFanout() {
        return this.intFanOut;
    }
    
    /**
     * <p>
     * Returns the scalar type of the terminal-level field values.
     * </p>
     * 
     * @return  scalar type of terminal-level structure field values. 
     */
    public JalScalarType   getType() {
        return this.facValues.getScalarType();
    }
    
    /**
     * <p>
     * Returns the seed value used to initialize the scalar value sequence for terminal structure 
     * fields.
     * </p>
     * 
     * @return  scalar value seed of the scalar factory provided at creation/construction  
     */
    public long  getSeed() {
        return  this.facValues.getSeed();
    }

    
    //
    // IDatumFactory Interface
    //
    
    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory#getDatumType()
     */
    @Override
    public DpSupportedType  getDatumType() {
        return ENM_DATUM_TYPE;
    }
    
    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory#getScalarType()
     */
    @Override
    public JalScalarType getScalarType() {
        return this.facValues.getScalarType();
    }

    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory#getComplexType()
     */
    @Override
    public JalComplexType getComplexType() {
        return ENM_CMPLX_TYPE;
    }
    
    /**
     * @see com.ospreydcs.dp.jal.tools.common.datagen.IDatumFactory#nextDatum()
     */
    @Override
    public Object nextDatum() {
        
        // Create structure
        List<Integer>   lstNodeIndex = new LinkedList<>();
        
        Object  objStruct = this.createStructure(lstNodeIndex);
        
        // Increase structure count (for unique field name generation)
        this.cntStructs++;
        
        return objStruct;
    }

    
    //
    // Support Methods
    //
    
    /**
     * </p>
     * Creates a (sub-)structure with <code>{@link #intFanOut}</code>
     * field (nodes), each having the same number of sub-fields, up to a depth of
     * <code>{@link #intDepth}</code>.
     * </p>
     * <p>
     * This is a recursive function and should be called initially using the argument
     * containing an empty node index list.
     * </p>
     * <p>
     * Terminal nodes are Java <code>Object</code> instances containing a scalar value
     * generated artificially (simulated value).  The data type of the scalar is prescribed
     * at construction.
     * </p>
     * 
     * @param lstNodeIndex  current node index within tree structure - use [] to start
     * 
     * @return a <code>Map</code> structure containing artificial field values 
     * 
     * @see #intDepth
     * @see #intFanOut
     * @see #facValues
     */
    private Map<String, Object> createStructure(List<Integer> lstNodeIndex) {

        // Check if we are at maximum depth 
        // - if so this is a terminal operation
        if (lstNodeIndex.size() + 1 >= this.intDepth) {

            // Create the final node map
            Map<String, Object> map = new TreeMap<>();
            
            // Populate the scalar values for each final node  
            for (int iFld = 0; iFld<intFanOut; iFld++) {

                // Create index for each terminal field
                List<Integer>   lstSubNodeIndex = new LinkedList<>(lstNodeIndex);
                lstSubNodeIndex.add(iFld);
                
                // Create name and scalar value for each terminal field
                String strFldNm = this.createNodeName(lstSubNodeIndex);
                Object objVal   = this.facValues.nextDatum();
                
                map.put(strFldNm, objVal);
            }
            
            return map;
        }
        
        // Otherwise we are at mid-depth within structure - Recursion
        // - create the map of fields and populate using recursion
        Map<String, Object> map = new TreeMap<>();
        
        for (int iFld = 0; iFld<intFanOut; iFld++) {
            List<Integer>   lstSubNodeIndex = new LinkedList<>(lstNodeIndex);
            lstSubNodeIndex.add(iFld);
            
            String strFldNm = this.createNodeName(lstSubNodeIndex);
            Object objFldVal = this.createStructure(lstSubNodeIndex);
            
            map.put(strFldNm, objFldVal);
        }
        
        return map;
    }
    
    /**
     * <p>
     * Creates a new structure node name.
     * </p>
     * <p>
     * Node names are created according to the index within the (tree) structure. 
     * If unique names are specified the structure number is prepended to the name.
     * </p> 
     * 
     * @param   lstNodeIndex    index of the node within the tree structure
     *  
     * @return  new node name corresponding to the given node index
     */
    private String  createNodeName(List<Integer> lstNodeIndex) {
        
        // The returned field name
        StringBuilder       bufNodeNm = new StringBuilder();
        
        // If field names are unique prefix with structure number
        if (this.bolUniqFldNms) {
            bufNodeNm.append(STR_UNIQ_FLD_NM_PREF);
            bufNodeNm.append(STR_UNIQ_FLD_NM_SEP_STRUCT_IND);
            bufNodeNm.append(this.cntStructs);
            bufNodeNm.append(STR_UNIQ_FLD_NM_SEP_PREF_TO_NM);
        }
        
        // Create field name with structure node index
        bufNodeNm.append(STR_FLD_NM_PREF);
        bufNodeNm.append(STR_FLD_NM_SEP);
        for (Integer intDepthIndex : lstNodeIndex) {
            bufNodeNm.append(intDepthIndex);
            bufNodeNm.append(STR_FLD_NM_SEP);
        }
        int     indLast = bufNodeNm.lastIndexOf(STR_FLD_NM_SEP);
        String  strNodeNm = bufNodeNm.substring(0, indLast);
        
        return strNodeNm;
    }
}
